### ISSUE TITLE
error with pipeline_rnaseqdiffexpression.py

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#104]
I have error with this pipeline by running the following command:

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGATPipelines/pipeline_rnaseqdiffexpression.py make loadEdgeR

I have the following error:
2015-01-14 15:40:11,991 ERROR Experiment.error.971 0: Task=aggregateFeatureCounts Error=CGAT.Pipeline.PipelineError Job=[[feature_counts.dir/THplus-AH016-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-JR036-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-MK002-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-MK144-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-NHDF1-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-OX119-R1.star_vs_genesetexons.tsv.gz]->feature_counts.dir/genesetexons.feature_counts.tsv.gz]:

                                                     Exception #1
                                                       'CGAT.Pipeline.PipelineError(---------------------------------------
                                                     Child was terminated by signal -1:
                                                     The stderr was:
                                                     Traceback (most recent call last):
                                                       File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py", line 641, in <module>
                                                         sys.exit(main(sys.argv))
                                                       File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py", line 635, in main
                                                         joinTables(options.stdout, options, args)
                                                       File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py", line 329, in joinTables
                                                         table[key] = [data[x] for x in take]
                                                     IndexError: list index out of range

                                                     python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py                                             --columns=1                                             --take=7                                             --use-file-prefix                                             --regex-filename='(.+)_vs.+.tsv.gz'                                             --log=feature_counts.dir/genesetexons.feature_counts.tsv.gz.log                                              feature_counts.dir/THplus-AH016-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-JR036-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-MK002-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-MK144-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-NHDF1-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-OX119-R1.star_vs_genesetexons.tsv.gz                   | sed 's/geneid/gene_id/'                   | gzip > feature_counts.dir/genesetexons.feature_counts.tsv.gz
                                                     -----------------------------------------)' raised in ...

**Comment by jethrojohnson** [comment]
Hi Cynthia,

Do the input files (e.g. THplus-JR036-R1.star_vs_genesetexons.tsv.gz) 
contain data? If so do they have seven columns?

It may be that you are running a different version of featureCounts, 
meaning the format of the count table is different (I know this code 
works with subread-1.4.6).





On 01/19/15 11:18, csandorfr wrote:
>
> I have error with this pipeline by running the following command:
>
> /net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGATPipelines/pipeline_rnaseqdiffexpression.py 
> make loadEdgeR
>
> I have the following error:
> 2015-01-14 15:40:11,991 ERROR Experiment.error.971 0: 
> Task=aggregateFeatureCounts Error=CGAT.Pipeline.PipelineError 
> Job=[[feature_counts.dir/THplus-AH016-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-JR036-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-MK002-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-MK144-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-NHDF1-R1.star_vs_genesetexons.tsv.gz,feature_counts.dir/THplus-OX119-R1.star_vs_genesetexons.tsv.gz]->feature_counts.dir/genesetexons.feature_counts.tsv.gz]:
>
> |                                                  Exception #1
>                                                     'CGAT.Pipeline.PipelineError(---------------------------------------
>                                                   Child was terminated by signal -1:
>                                                   The stderr was:
>                                                   Traceback (most recent call last):
>                                                     File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py", line 641, in <module>
>                                                       sys.exit(main(sys.argv))
>                                                     File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py", line 635, in main
>                                                       joinTables(options.stdout, options, args)
>                                                     File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py", line 329, in joinTables
>                                                       table[key] = [data[x] for x in take]
>                                                   IndexError: list index out of range
>
>                                                   python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/combine_tables.py                                             --columns=1                                             --take=7                                             --use-file-prefix                                             --regex-filename='(.+)_vs.+.tsv.gz'                                             --log=feature_counts.dir/genesetexons.feature_counts.tsv.gz.log                                              feature_counts.dir/THplus-AH016-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-JR036-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-MK002-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-MK144-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-NHDF1-R1.star_vs_genesetexons.tsv.gz feature_counts.dir/THplus-OX119-R1.star_vs_genesetexons.tsv.gz                   | sed 's/geneid/gene_id/'                   | gzip > feature_counts.dir/g
>   enesetexons.feature_counts.tsv.gz
>                                                   -----------------------------------------)' raised in ...
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CGATOxford/cgat/issues/104>.
>


-- 
Dr Jethro Johnson
CGAT Genomics Training Fellow
MRC Functional Genomics Unit
University of Oxford
+44 1865 282362

**Comment by csandorfr** [comment]
Yes it contains data:

-rw-r--r--. 1 cynthias cppgroup 3076250 Jan 14 15:38 THplus-JR036-R1.star_vs_genesetexons.tsv.gz

However it contains 6 columns

['Geneid', 'Chr', 'Start', 'End', 'Strand', 'Length']
['ENSG00000223972', 'chr1;chr1;chr1;chr1', '11869;12595;12975;13221', '12227;12721;13052;14412', '+;+;+;+', '1756']

by examining the log file generated by subread I use the version: v1.4.6

**Comment by jethrojohnson** [comment]
The last column in the featureCounts table contains the count data.

For some reason these are missing in your data. Is there any error in 
the log file THplus-JR036-R1.star_vs_genesetexons.tsv.log?
Alternatively, what happens when you run the same featureCounts command 
(see PipelineRnaseq.py line 800) from the command line?

On 01/19/15 11:41, csandorfr wrote:
>
> Yes it contains data:
>
> -rw-r--r--. 1 cynthias cppgroup 3076250 Jan 14 15:38 
> THplus-JR036-R1.star_vs_genesetexons.tsv.gz
>
> However it contains 6 columns
>
> ['Geneid', 'Chr', 'Start', 'End', 'Strand', 'Length']
> ['ENSG00000223972', 'chr1;chr1;chr1;chr1', '11869;12595;12975;13221', 
> '12227;12721;13052;14412', '+;+;+;+', '1756']
>
> by examining the log file generated by subread I use the version: v1.4.6
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CGATOxford/cgat/issues/104#issuecomment-70480865>.
>


-- 
Dr Jethro Johnson
CGAT Genomics Training Fellow
MRC Functional Genomics Unit
University of Oxford
+44 1865 282362

**Comment by csandorfr** [comment]
Ok,

I removed the directories *.dir and I re-ran the same command.

The error come from:  buildFeatureCounts

I have the same error of tempory file than with pipeline_mapping.py (not resolved)

Task=buildFeatureCounts Error=exceptions.OSError Job=[[THplus-AH016-R1.star.bam,genesetexons.gtf.gz]->feature_counts.dir/THplus-AH016-R1.star_vs_genesetexons.tsv.gz]: ([Errno 2] No such file or directory: '/scratch/ctmpb1Vy5T')

Thanks

Cynthia
