### ISSUE TITLE
farm.py broken?

### ISSUE THREAD

**Issue by snsansom** [CGATOxford/cgat#113]
farm.py does not appear to me to be behaving as expected.

For example:

cat /ifs/mirror/genomes/plain/dm3.fasta | python scripts/farm.py --split-at-regex="^>(\S+)" "wc -c"

Just gives an error (TypeError: unsupported operand type(s) for %: 'int' and 'NoneType').

I ran across this because "buildNUMPTs" in pipeline_annotations.py is failing on my system due to a different farm.py error (to do with nfields == None -  which also trips up a warning call expecting an int...!).

Also there don't appear to be any tests for farm.py?

**Comment by snsansom** [comment]
As an example (command taken from pipeline_annotations.py log) running the following in /ifs/projects/stephens/farm.py/  (i.e. on the CGAT cluster):

##################################
python /ifs/devel/stephens/cgat/scripts/index_fasta.py    --extract=chrM  --log=numts.gtf.gz.log            /ifs/mirror/genomes/plain/mm10     > tmpfile; cat /ifs/mirror/genomes/plain/mm10.fasta     | python /ifs/devel/stephens/cgat/scripts/farm.py                  --method=drmaa --cluster-priority=-10 --cluster-queue=all.q --cluster-num-jobs=100 --bashrc=/ifs/devel/stephens/cgat/scripts/bashrc.cgat  --cluster-options=""  --split-at-regex="^>(\S+)" --chunk-size=1 --log=numts.gtf.gz.log     "exonerate --target %STDIN%               --query tmpfile  --model affine:local --score 100               --showalignment no --showsugar no --showcigar no     --showvulgar no               --ryo \"%qi\\t%qS\\t%qab\\t%qae\\t%ti\\t%tS\\t%tab\\t%tae\\t%s\\t%pi\\t%C\n\"      "      | grep -v -e "exonerate" -e "Hostname"     | gzip > numts.gtf.gz.links.gz
###################################

gives the following error:

Traceback (most recent call last):
  File "/ifs/devel/stephens/cgat/scripts/farm.py", line 1183, in <module>
    sys.exit(main())
  File "/ifs/devel/stephens/cgat/scripts/farm.py", line 1094, in main
    )(started_requests, options.stdout, options)
  File "/ifs/devel/stephens/cgat/scripts/farm.py", line 420, in __call__
    (l[:-1], nfields, self.nfields))
TypeError: %d format: a number is required, not NoneType

**Comment by AndreasHeger** [comment]
Thanks, already fixed, but have not pushed changes. Will try to do tonight. Best, andreas                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone on the EE network.                                                                                                                                                                                                                                         From: Steve SansomSent: Wednesday, 28 January 2015 13:22To: CGATOxford/cgatReply To: CGATOxford/cgatSubject: Re: [cgat] farm.py broken? (#113)As an example (command taken from pipeline_annotations.py log) running the following in /ifs/projects/stephens/farm.py/  (i.e. on the CGAT cluster):

##################################
python /ifs/devel/stephens/cgat/scripts/index_fasta.py    --extract=chrM  --log=numts.gtf.gz.log            /ifs/mirror/genomes/plain/mm10     > tmpfile; cat /ifs/mirror/genomes/plain/mm10.fasta     | python /ifs/devel/stephens/cgat/scripts/farm.py                  --method=drmaa --cluster-priority=-10 --cluster-queue=all.q --cluster-num-jobs=100 --bashrc=/ifs/devel/stephens/cgat/scripts/bashrc.cgat  --cluster-options=""  --split-at-regex="^>(\S+)" --chunk-size=1 --log=numts.gtf.gz.log     "exonerate --target %STDIN%               --query tmpfile  --model affine:local --score 100               --showalignment no --showsugar no --showcigar no     --showvulgar no               --ryo \"%qi\t%qS\t%qab\t%qae\t%ti\t%tS\t%tab\t%tae\t%s\t%pi\t%C\n\"      "      | grep -v -e "exonerate" -e "Hostname"     | gzip > numts.gtf.gz.links.gz
###################################

gives the following error:

Traceback (most recent call last):
  File "/ifs/devel/stephens/cgat/scripts/farm.py", line 1183, in 
    sys.exit(main())
  File "/ifs/devel/stephens/cgat/scripts/farm.py", line 1094, in main
    )(started_requests, options.stdout, options)
  File "/ifs/devel/stephens/cgat/scripts/farm.py", line 420, in call
    (l[:-1], nfields, self.nfields))
TypeError: %d format: a number is required, not NoneType

—Reply to this email directly or view it on GitHub.

**Comment by AndreasHeger** [comment]
@snsansom, farm.py is best tested on the cluster. pipeline_testing does this implicitely.

**Comment by snsansom** [comment]
Many thanks for looking at this. 

After your commits the pipelines_anntotations test works, but the simple:

cat /ifs/mirror/genomes/plain/dm3.fasta | python scripts/farm.py --split-at-regex="^>(\S+)" "wc -c"

appears to still gives an error - not sure if this is now by design?

**Comment by Acribbs** [comment]
Have closed but please reopen if necessary
