### ISSUE TITLE
pipeline_mapping issue with gsnap

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#118]
Hi,

I'm trying to run the pipeline mapping with gsnap:

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGATPipelines/pipeline_mapping.py -v5 --local make mapReadsWithGSNAP

I have bam file empty and in the log bam file I have the following error:

Reading splicing file gsnap.dir/splicesites.iit locally...found donor and acceptor tags, so treating as splicesites file
splice distances present...555679 unique splicesites...
555679 splicesites are valid...3482 entries with distance > 200000 specified for local splice distance...splicetrie_obs has 2477114 entries...splicetrie_max has 80893303 entries...done
GMAP modes: pairsearch, indel_knownsplice, terminal, improvement
Starting alignment
Processed 17737303 queries in 42501.31 seconds (417.34 queries/sec)
[bam_header_read] invalid BAM binary header (this is not a BAM file). 

I tried to run each command of mapReadsWithGSNAP:

The mapping works I have sam file in my tempory directory:

command:
 /net/isi-scratch/src/gmap-2014-05-15/bin/gsnap -B3               --nthreads 9                --format=sam                --db=/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ALIGN/GSNAP_CGAT/index_gsnap/hg19           -D /net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ALIGN/GSNAP_CGAT/index_gsnap -d hg19 --use-splicing=gsnap.dir/splicesites.iit                 <( zcat ./THplus-AH016-1-R1.fastq.1.gz ) <( zcat ./THplus-AH016-1-R1.fastq.2.gz )                > /net/isi-scratch/cynthia/tmp/ctmpxk0fPZ/THplus-AH016-1-R1.gsnap.sam

The header of my sam file is:

bash-4.1$ head /net/isi-scratch/cynthia/tmp/ctmpxk0fPZ/THplus-AH016-1-R1.gsnap.sam
@HD     VN:1.0  SO:unsorted
@PG     ID:GSNAP        PN:gsnap        VN:2014-05-15   CL:/net/isi-scratch/src/gmap-2014-05-15/bin/gsnap -B3 --nthreads 9 --format=sam --db=/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ALIGN/GSNAP_CGAT/index_gsnap/hg19 -D /net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ALIGN/GSNAP_CGAT/index_gsnap -d hg19 --use-splicing=gsnap.dir/splicesites.iit /dev/fd/63 /dev/fd/62
@SQ     SN:chr1 LN:249250621
@SQ     SN:chr2 LN:243199373
@SQ     SN:chr3 LN:198022430
@SQ     SN:chr4 LN:191154276
@SQ     SN:chr5 LN:180915260
@SQ     SN:chr6 LN:171115067
@SQ     SN:chr7 LN:159138663
@SQ     SN:chr8 LN:146364022

However the next command to change the format (sam to bam file) send me an error:

samtools view -uS /net/isi-scratch/cynthia/tmp/ctmpxk0fPZ/THplus-AH016-1-R1.gsnap.sam                                  | python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/bam2bam.py             --strip-method=all             --method=strip-sequence --log=gsnap.dir/THplus-AH016-1-R1.gsnap.bam.log                 | samtools sort - gsnap.dir/THplus-AH016-1-R1.gsnap 2>>gsnap.dir/THplus-AH016-1-R1.gsnap.bam.log

 samtools view -uS /net/isi-scratch/cynthia/tmp/ctmpxk0fPZ/THplus-AH016-1-R1.gsnap.sam                                  | python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/bam2bam.py             --strip-method=all             --method=strip-sequence --log=gsnap.dir/THplus-AH016-1-R1.gsnap.bam.log                 | samtools sort - gsnap.dir/THplus-AH016-1-R1.gsnap 2>>gsnap.dir/THplus-AH016-1-R1.gsnap.bam.log
[samopen] SAM header is present: 93 sequences.

Error compiling Cython file:
------------------------------------------------------------
...
    cdef bint c_remove_mismatches = remove_mismatches
    cdef bint c_remove_unmapped = remove_unmapped

    cdef int * remove_contig_tids 
    cdef int nremove_contig_tids = 0
    cdef AlignedSegment read
        ^
------------------------------------------------------------

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.pyx:97:9: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cdef bint c_remove_unmapped = remove_unmapped

    cdef int * remove_contig_tids 
    cdef int nremove_contig_tids = 0
    cdef AlignedSegment read
    cdef AlignedSegment match
        ^
------------------------------------------------------------

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.pyx:98:9: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            continue

        # remove non-unique alignments
        if c_remove_nonunique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
                               ^
------------------------------------------------------------

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.pyx:179:32: Cannot convert Python object to 'bam1_t const *'

Error compiling Cython file:
------------------------------------------------------------
...
        # remove non-unique alignments
        if c_remove_nonunique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
            if v == NULL:
                v = bam_aux_get(read._delegate, 'X0')
                                   ^
------------------------------------------------------------

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.pyx:181:36: Cannot convert Python object to 'bam1_t const *'

Error compiling Cython file:
------------------------------------------------------------
...
                    nnonunique += 1
                    continue
        # remove unique alignments
        elif c_remove_unique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
                               ^
------------------------------------------------------------

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.pyx:191:32: Cannot convert Python object to 'bam1_t const *'

Error compiling Cython file:
------------------------------------------------------------
...
        # remove unique alignments
        elif c_remove_unique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
            if v == NULL:
                v = bam_aux_get(read._delegate, 'X0')
                                   ^
------------------------------------------------------------

/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.pyx:193:36: Cannot convert Python object to 'bam1_t const *'
/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/_bam2bam.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
Traceback (most recent call last):
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/bam2bam.py", line 143, in <module>
    import CGAT._bam2bam as _bam2bam
ImportError: /net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/_bam2bam.so: undefined symbol: bam_destroy1
Segmentation fault (core dumped)

Any idea why it does not works?

Thanks

Cynthia

**Comment by AntonioJBT** [comment]
Hi Cynthia,
You may need to rebuild extensions (may be due to changes from pysam 0.8.1)?
If so, update changes to your repository and run:

python setup.py develop
python scripts/cgat_rebuild_extensions.py

and re-run the pipeline.
Antonio

**Comment by csandorfr** [comment]
I tried but I have this error: 

python setup.py develop
running develop
running egg_info
writing requirements to CGAT.egg-info/requires.txt
writing CGAT.egg-info/PKG-INFO
writing top-level names to CGAT.egg-info/top_level.txt
writing dependency_links to CGAT.egg-info/dependency_links.txt
writing entry points to CGAT.egg-info/entry_points.txt
reading manifest file 'CGAT.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'CGAT.egg-info/SOURCES.txt'
running build_ext
skipping 'CGAT/Components/Components.cpp' Cython extension (up-to-date)
skipping 'CGAT/NCL/cnestedlist.c' Cython extension (up-to-date)
cythoning scripts/_bam2bam.pyx to scripts/_bam2bam.c

Error compiling Cython file:
------------------------------------------------------------
...
    cdef bint c_remove_mismatches = remove_mismatches
    cdef bint c_remove_unmapped = remove_unmapped

    cdef int * remove_contig_tids 
    cdef int nremove_contig_tids = 0
    cdef AlignedSegment read
        ^
------------------------------------------------------------

scripts/_bam2bam.pyx:97:9: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cdef bint c_remove_unmapped = remove_unmapped

    cdef int * remove_contig_tids 
    cdef int nremove_contig_tids = 0
    cdef AlignedSegment read
    cdef AlignedSegment match
        ^
------------------------------------------------------------

scripts/_bam2bam.pyx:98:9: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            continue

        # remove non-unique alignments
        if c_remove_nonunique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
                               ^
------------------------------------------------------------

scripts/_bam2bam.pyx:179:32: Cannot convert Python object to 'bam1_t const *'

Error compiling Cython file:
------------------------------------------------------------
...
        # remove non-unique alignments
        if c_remove_nonunique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
            if v == NULL:
                v = bam_aux_get(read._delegate, 'X0')
                                   ^
------------------------------------------------------------

scripts/_bam2bam.pyx:181:36: Cannot convert Python object to 'bam1_t const *'

Error compiling Cython file:
------------------------------------------------------------
...
                    nnonunique += 1
                    continue
        # remove unique alignments
        elif c_remove_unique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
                               ^
------------------------------------------------------------

scripts/_bam2bam.pyx:191:32: Cannot convert Python object to 'bam1_t const *'

Error compiling Cython file:
------------------------------------------------------------
...
        # remove unique alignments
        elif c_remove_unique:
            # check either NH or X0 (bwa) flag
            v = bam_aux_get(read._delegate, 'NH')
            if v == NULL:
                v = bam_aux_get(read._delegate, 'X0')
                                   ^
------------------------------------------------------------

scripts/_bam2bam.pyx:193:36: Cannot convert Python object to 'bam1_t const *'
building 'CGAT._bam2bam' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -I/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/numpy-1.9.0-py2.7-linux-x86_64.egg/numpy/core/include -I/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/pysam -I/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/pysam/include/htslib -I/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/pysam/include/samtools -I/net/isi-scratch/cynthia/CGAT-DEPS/Python-2.7.6_enable_shared/include/python2.7 -c scripts/_bam2bam.c -o build/temp.linux-x86_64-2.7/scripts/_bam2bam.o
scripts/_bam2bam.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1

**Comment by AndreasHeger** [comment]
@csandorfr, I think you pysam might be out-of-date - what version do you have installed (the latest is 0.8.1).

**Comment by csandorfr** [comment]
It works

I had this version of pysyam
>>> print pysam.__version__
0.8.0

I updated my version of pysam:

pip install pysam --upgrade

>>> print pysam.__version__
0.8.1

and rebuild my extensions:

python setup.py develop 
python scripts/cgat_rebuild_extensions.py

Many Thanks
