### ISSUE TITLE
Automatic detection of adapter contamination for preprocessing

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/cgat#120]
Currently, the readqc pipeline can identify overrepresented sequences (FastQC) and remove them with various preprocessing tools (Trimmomatic, cutadapt, etc). However, it is up to the user to specify the sequences for the adapters.

Proposed solution within readqc:
1. Parse fastqc output to identify contaminating adapters (by name)
2. Use a dictionary of illumina adapters etc to convert to sequences {adapter_name : seq} 
3. Generate either a comma separated list (as used by cutadapt) or a temporary fasta file (as used by trimmomatic) to be passed onto the read processing step

This should be an optional step which will (overide/append to ?) user supplied adapter sequence or fasta file specified in pipeline.ini.

**Comment by TomSmithCGAT** [comment]
@MikeDMorgan 
This can be closed now, right?

**Comment by MikeDMorgan** [comment]
The branch has been merged.  The current fix is a little rudimentary and will raise an AttributeError if there are no overrepresented sequences.  The ideal solution would be to simply pass over this function and ignore this paramter.  Not sure how to implement it without manipulating the PARAMs dict (bad) or using a global variable (also bad).
