### ISSUE TITLE
Conda install cgat-devel-lite

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#126]
Hi Guys,

I've been trying to install the cgat-devel-lite conda package.

First I create a conda environment with the cgat-devel-lite package in it:

```
conda create -n cgat-devel-lite cgat-devel-lite
```

then I clone the code base:

```
git clone git@github.com:CGATOxford/cgat.git
```

This all works fine. The problem comes when I try to compile the cloned code:

```
python setup.py develop
```

gives the following error

```
Searching for seaborn>=0.3.1
Reading https://pypi.python.org/simple/seaborn/
Best match: seaborn 0.5.1
Downloading https://pypi.python.org/packages/source/s/seaborn/seaborn-0.5.1.tar.gz#md5=2ce6ea7d3c67858c0b1f5793fa2043b8
Processing seaborn-0.5.1.tar.gz
Writing /tmp/easy_install-AHrMjc/seaborn-0.5.1/setup.cfg
Running seaborn-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-AHrMjc/seaborn-0.5.1/egg-dist-tmp-ti58Fq
error: SandboxViolation: os.open(u'/home/mb1ims/.config/matplotlib/tmpflXF8s', 131266, 384) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

This can be fixed by doing

```
conda install seaborn=0.5.1
```

But that kind of defeats the object of using the conda environment doesn't it?

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

Have you enabled the conda environment:
```
source /path/to/conda/bin activate cgat-devel-lite
```

before doing:
```
python setup.py develop
```

?

I have been looking at the `cgat-devel-lite` package and `seaborn` is not a direct dependency in there but in `cgatreport`. No sure whether this is a conda issue or not.

**Comment by IanSudbery** [comment]
Hi Sebastian



Yes, the environment was activated. I also noticed that when I tried to
install ipython, it didn’t install the correct dependencies either.



Ian





*From:* Sebastian Luna Valero [mailto:notifications@github.com]
*Sent:* 06 February 2015 17:33
*To:* CGATOxford/cgat
*Cc:* Ian Sudbery
*Subject:* Re: [cgat] Conda install cgat-devel-lite (#126)



Hi Ian,

Have you enabled the conda environment:

source /path/to/conda/bin activate cgat-devel-lite

before doing:

python setup.py develop

?

I have been looking at the cgat-devel-lite package and seaborn is not a
direct dependency in there but in cgatreport. No sure whether this is a
conda issue or not.

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/cgat/issues/126#issuecomment-73278754>.
