### ISSUE TITLE
mergeBAMfiles in pipeline_mapping

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#131]
I was wondering why the function mergeBAMfiles was removed in pipeline_mapping

python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGATPipelines/pipeline_mapping.py -v5 --local make mergeBAMFiles

 Target task 'mergeBAMFiles' is not a pipelined task in Ruffus. Have you mis-spelt the function name?

**Comment by AndreasHeger** [comment]
mergeBAMfiles is only visible if the regular expresssion
telling which files should be merged are set:

```
if "merge_pattern_input" in PARAMS and PARAMS["merge_pattern_input"]:
```

Could this be the reason?

Best wishes,
Andreas

**Comment by csandorfr** [comment]
Hi Andreas,

OK I should fill in pipeline.ini:

pattern_input=
pattern_output=

However I was wondering what function I have run with pipeline_mapping to just merge bam file and avoid to re-align my fasq file 

Thanks

Cynthia

**Comment by csandorfr** [comment]
Thanks

it works...

I added the parameters in my parameters.ini and I ran mergeBAMFiles
