### ISSUE TITLE
edgeR pipeline_rnaseqdiffexpression.py

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#149]
By performing differential expression  by using the following design:

track   include group   pair
THplus-NHDF1-R1.star    1       Ctr     1
THplus-OX119-R1.star    1       Ctr     1
THplus-AH016-R1.star    1       Ctr     1
THplus-JR036-R1.star    1       Case    1
THplus-MK144-R1.star    1       Case    1
THplus-MK002-R1.star    1       Case    1

I got 1122 differential expressed gene with the functions loadedgeR . This number is really big compared with cuffdiff, deseq,deseq2

I re-peformed the same analyses directly with edgeR from count file:

exp <-read.table("/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/scripts/edgeR/matrix_deseq_feature_filter.tsv",header=TRUE, sep = "\t",row.names=1)
exp_mat<-data.matrix(exp, rownames.force = NA)
Pheno<-read.table("/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/scripts/edgeR/info_sample.txt",header=TRUE,sep="\t",row.names=1)
d <- DGEList(counts=exp_mat,group=factor(Pheno$Status))
d1 <- estimateCommonDisp(d, verbose=T)
d1 <- estimateTagwiseDisp(d1)
et12 <- exactTest(d1)

I got 40 genes q-value < 0.1 

I was wondering what can be explain the different between both analyses.

Thanks

Cynthia

**Comment by TomSmithCGAT** [comment]
Hi Cynthia,

By default, edger is currently set to run genewise generalised linear models with the model as ~countsTable$samples$groups. It looks like you've used Fisher's exact test below which I guess is the reason for the difference.

I'm actually in the process of re-writing our code for differential expression analysis with Jethro. One of the features we're going to add is more flexibility for the user to define the model and statistical test. Hopefully we'll have something working for edgeR by the end of this week and then onto DESeq & DESeq2.

Regards,

Tom

Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
________________________________

**Comment by csandorfr** [comment]
Hi Tim,

I tried with GLM and I don't have the same number of DE.

design.mat <- model.matrix(~  d$samples$group)
d2 <- estimateGLMCommonDisp(d,design.mat)
d2 <- estimateGLMTrendedDisp(d2,design.mat, method="power")
d2 <- estimateGLMTagwiseDisp(d2,design.mat)
fit <- glmFit(d2, design.mat)
de2 <- decideTestsDGE(lrt12, adjust.method="BH", p.value = 0.1)
summary(de2)
   [,1] 
-1    40
0  22967
1     26

Thanks

Cynthia
