### ISSUE TITLE
Sra.extract runs extraction locally

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#151]
I'm currently trying to run the mapping pipeline on some SRA files. The mapping pipeline appears to be configured to extract these files on the local machine. This means that

a) The process is going very slowly
b) I've been using 4 full cpus on the head node (despite there only being two SRA files??) for nearly 2 hours now.

**Comment by AndreasHeger** [comment]
Thanks. @TomSmithCGAT , can you please have a look? It might be related to you introduction of the SRA module.

Note: SRA.exract should be SRA.extract in PipelineMapping.py?

**Comment by IanSudbery** [comment]
> Note: SRA.exract should be SRA.extract in PipelineMapping.py?



I already fixed this: I’ll push a branch that Tom can work on.



*From:* Andreas Heger [mailto:notifications@github.com]
*Sent:* 24 February 2015 17:06
*To:* CGATOxford/cgat
*Cc:* Ian Sudbery
*Subject:* Re: [cgat] Sra.extract runs extraction locally (#151)



Thanks. @TomSmithCGAT <https://github.com/TomSmithCGAT> , can you please
have a look? It might be related to you introduction of the SRA module.

Note: SRA.exract should be SRA.extract in PipelineMapping.py?

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/cgat/issues/151#issuecomment-75797993>.

**Comment by IanSudbery** [comment]
Okay, I've now pushed a branch fixing_sra with that fix in

**Comment by IanSudbery** [comment]
Also, because the extraction is done locally, it exacts to a local scratch and then submits to the cluster, which trys to read from the now none existant extracted fastq file. 

As I see it, there are three options:
1) The fastq-dump lines need to be added to the mapping statement in the preprocess stage, rather than actually run at the time of compiling the mapping statement. If this is the case the dump will run each time a mapping is run. This is at least twice, because all mapping runs run the nreads mapper as well as the specified mapper.

2) The fastqs are dumped at statement compilation time (but please lets run on the cluster), and saved to /ifs/scratch. The only beneift of this over 1 is that it is more in keeping with the current logic.

3) There is a conversion step that makes a permanent conversion of sra to fastq, saved in the pipeline directory, that can then be used in all down stream mapping tasks: this is the more compute efficient mechanism, but not so space efficient.

**Comment by TomSmithCGAT** [comment]
The code in the sra module is essentially just a copy of what was previously in PipelineMapping. I don't think I changed the workflow for mapping from .sra files.

My thoughts:

1) Easy to implement - Just need to change line 472 in PipelineMapping.py
outdir = P.getTempDir() --> outdir = P.getTempDir(/ifs/scratch) 

and make Sra.extract return a statement to be added to cmd_preprocess rather than running fastq.dump locally with P.execute().

It does seem very wasteful extracting the files each time a mapper is called though, especially if it's just to count reads!

2) I'm not sure how this would differ from option 1?

3) My understanding is that this would need to be implemented in pipeline_mapping.py. Without executing Sra.sneak within the pipeline (i.e outside any decorated functions), I can't see how we can make ruffus  pick up the extracted fastqs for the downstream targets.

Maybe I'm missing something here?

**Comment by AndreasHeger** [comment]
Thanks, @TomSmithCGAT 

1)  avoid using /ifs/scratch or similar - use the mechanisms supplied by Pipeline.py. Otherwise your code will not be portable.

3) disk space is more precious to us than compute.

I think what @IanSudbery means that the extraction is part of the job subscript that is send to the cluster. This is how it used to be. The extract method uses P.execute() which will execute a command locally, i.e. not remotely. You will need to use method 2.

Finally, can you rename Sra.sneak. I am not sure what sneaking means in this context. Typically used is "peek" to look inside a file.

Thanks!

**Comment by IanSudbery** [comment]
Hi,



The difference between 1 and 2 is that in one, the temporary file is store
on the local scratch space on the node. This is more performant than
storing the files on /ifs/scratch. Indeed so much so that I believe the
fastq mappers actually copy the fastq file to the node before mapping them.



Ian





*From:* Andreas Heger [mailto:notifications@github.com]
*Sent:* 26 February 2015 17:04
*To:* CGATOxford/cgat
*Cc:* Ian Sudbery
*Subject:* Re: [cgat] Sra.extract runs extraction locally (#151)



Thanks, @TomSmithCGAT <https://github.com/TomSmithCGAT>

1) avoid using /ifs/scratch or similar - use the mechanisms supplied by
Pipeline.py. Otherwise your code will not be portable.

3) disk space is more precious to us than compute.

I think what @IanSudbery <https://github.com/IanSudbery> means that the
extraction is part of the job subscript that is send to the cluster. This
is how it used to be. The extract method uses P.execute() which will
execute a command locally, i.e. not remotely. You will need to use method 2.

Finally, can you rename Sra.sneak. I am not sure what sneaking means in
this context. Typically used is "peek" to look inside a file.

Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/cgat/issues/151#issuecomment-76218587>.

**Comment by AndreasHeger** [comment]
Indeed. Avoid shared scratch unless absolutely necessary. Almost always use local scratch.

**Comment by TomSmithCGAT** [comment]
@IanSudbery and @AndreasHeger. Thanks for the clarifications.

I take it from this all I need to do is make Sra.extract() return a statement when called from PipelineMapping to be included in the preprocess portion of the mapping statement. That way the resulting fastqs will be stored on the node scratch where and will be available for the downstream mapping?

I'll rename sneak to peek as well. It looks I was lead astray by the previous comments in PipelineMapping...
"
# sneak preview to determine if paired end or single end
P.execute(
"""fastq-dump --split-files --gzip -X 1000
--outdir %(outdir)s %(infile)s""" % locals())
"

**Comment by IanSudbery** [comment]
Sounds like a suitable solution to me. Do you want me to implement it or
will you?



*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 26 February 2015 17:23
*To:* CGATOxford/cgat
*Cc:* Ian Sudbery
*Subject:* Re: [cgat] Sra.extract runs extraction locally (#151)



@IanSudbery <https://github.com/IanSudbery> and @AndreasHeger
<https://github.com/AndreasHeger>. Thanks for the clarifications.

I take it from this all I need to do is make Sra.extract() return a
statement when called from PipelineMapping to be included in the preprocess
portion of the mapping statement. That way the resulting fastqs will be
stored on the node scratch where and will be available for the downstream
mapping?

I'll rename sneak to peek as well. It looks I was lead astray by the
previous comments in PipelineMapping...
"
sneak preview to determine if paired end or single end

P.execute(
"""fastq-dump --split-files --gzip -X 1000
--outdir %(outdir)s %(infile)s""" % locals())
"

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/cgat/issues/151#issuecomment-76222565>.[image:
Image removed by sender.]

**Comment by TomSmithCGAT** [comment]
@IanSudbery I've done it. I'm Just checking it runs OK with one of my .sra files before I push it back

**Comment by TomSmithCGAT** [comment]
@IanSudbery Another possible issue though. The preprocess statement standardises fastq files to +33 format for the downstream tools which either only accept +33 formatted fastqs (BWA) or default to +33 (Bowtie). Tophat and Tophat2 autodetect format. Not sure about GSNAP, STAR etc. 

Should we detect the format from the first 1000 lines within the call to Sra.peek() and then add a call to fastq2fastq if required?

**Comment by IanSudbery** [comment]
@TomSmithCGAT If the call to sra is added early enough, can we not just use the same process that is used for fastq inputs?

**Comment by TomSmithCGAT** [comment]
@IanSudbery 

Yeah, that's what I did. Sra.peek() now also checks the format of the first fastq file and returns the format along with the fastq names. In PipelineMapping, the format is checked for "Sanger" and a call to fastq2fastq added to the mapping statement if required. The FixSRA branch has been merged back into master.
