### ISSUE TITLE
counts2counts.py requires --spike-keep-column-suffix

### ISSUE THREAD

**Issue by MikeDMorgan** [CGATOxford/cgat#165]
Currently counts2counts.py requires the option `--spike-keep-column-suffix`.  If this option is not supplied there is no alternative behaviour that prevents errors downstream.

Proposed fix: if option not provided take suffixes from design matrix tracks as the default behaviour.

**Comment by MikeDMorgan** [comment]
Spike-in behviour assumes pairs == 1 as rather than 0 as indicated in the documentation for unpaired designs.  Add in assert statement to handle unpaired data.

**Comment by MikeDMorgan** [comment]
addendum to this issue - unexpected behaviour with spike will output all values outside of the specified range.

**Comment by TomSmithCGAT** [comment]
@MikeDMorgan 

I've been meaning to re-write counts2counts.py so this seems like a good time to start.

I opened a new branch and checked out your version of counts2counts.py from the MM-counts2counts_design_issue branch.

The workflow in counts2counts now uses the Counts and Design objects in Counts.py and Expression.py and should be a little clearer what it's doing.

The unexpected outputting of spikes outside the specified bin range has also been resolved (hopefully...)

I'll submit a pull request shortly but if you want the updated files before then, you can checkout the relevant files from my branch:

git checkout TS-Counts2countsRewrite -- CGAT/Counts.py
git checkout TS-Counts2countsRewrite -- CGAT/Expression.py
git checkout TS-Counts2countsRewrite -- scripts/counts2counts.py

**Comment by TomSmithCGAT** [comment]
@MikeDMorgan I assume this can be closed now?
