### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by pengchy** [CGATOxford/cgat#166]
Following the installation instructions, I listed the command used to install CGAT:
```
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
virtualenv --no-site-packages cgat-python
source cgat-python/bin/activate
wget https://raw.github.com/CGATOxford/cgat/master/requires.txt
while read line ; do echo $line > x ; pip install -r x; rm x; done < requires.txt
pip install cgat
```
However, when the installation hits the last step, I am stuck with the error
```
freetype: no  [Requires freetype2 2.3 or later.  Found 2.2.1.]

============================================================================

                        * The following required packages can not be built:

                        * freetype

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /panfs/home/kang/yangpc/soft/01.NGS_data_process/CGAT/cgat-python/build/matplotlib
```

I have already installed the latest freetype version 2.5.5 and add the library path to the variable LD_LIBRARY_PATH at the beginning. However, this error still exist. The version 2.2.1 is installed by system administrator. It seems CGAT can only detect system default library, not able to using the customized library with LD_LIBRARY_PATH. Does anyone have any idea for this condition?

Best,
Pengcheng Yang
BIOLS, CAS

**Comment by AndreasHeger** [comment]
Hi Pengcheng,

this seems to be a matplotlib error - can you try installing matplotlib
separately?

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Closing for now.
