### ISSUE TITLE
ImportError: No module named CGATPipelines.Local

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/cgat#170]
Hi,

The following test fail:
```
tests/gpipe_export_code.py/version
```

The error message is:
```
ImportError: No module named CGATPipelines.Local
```

Details here:
https://travis-ci.org/CGATOxford/cgat/jobs/57975048

Could somebody please have a look?

Thanks!

**Comment by AndreasHeger** [comment]
Thanks, this has been fixed in 679aa0cc18ee84a6bc2164d394c6bdfe7487334d
Please reopen if it persists.
Best , Andreas
