### ISSUE TITLE
Add Database-based filtering to gtf2gtf.py

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/cgat#179]
The latest ENSEMBL GTFs have the gene_biotype information stored in as an attribute. Previously this was also included in column 2 ("source"). There are occasions when we want to filter a GTF which no longer contains the gene_biotype attribute, for example after passing through Cuffdiff to add p_id and tss_ids. 

Furthermore, the current method searches for the filter tag, e.g "protein_coding" in the "source" or anywhere in the attributes. This leads to GTF entries with gene_biotype = "polymorphic_pseudogene" but "transcript_biotype = "protein_coding" being included which may not be expected by the user (see note below).

One solution would be to enable database-based filtering in gtf2gtf.py, e.g filter the gtf using the gene_info table in the annotations database. Filtering using a database, we can specify the exact attributes we want to look within for the filter tag.

NOTE: We may actually want to include the aforementioned polymorphic genes when filtering for "protein_coding" but if so it should be clear from the gtf2gtf documentation that these will be included.

**Comment by TomSmithCGAT** [comment]
@AndreasHeger I've implemented this in a simple form on the branch TS-AddDatabaseBasedFilteringToGtf2gtf. Currently, the script expects the database table to contain columns "gene_id" and "gene_biotype". I think we might also like to add the option to specify the attribute columns to extract so that "transcript_biotype" etc could be extracted also.

Could you take a look at my implementation and see if it's suitable.

**Comment by AndreasHeger** [comment]
Sorry, I have not been clear. What I meant is that filtering by gene_id is already possible in gtf2gtf. So the solution is to write a table with gene_ids of a certain attribute set to file and then call gtf2gtf. Thus the solution is on a user level.

Scripts should not need database access. We don't want to proscribe users to use a particular database schema or implementation. Database access requires username, password, hostname, ports and standards for database, schema, table, column name, column type, ....., which is all a bit much for gtf2gtf to ask for.

**Comment by TomSmithCGAT** [comment]
@AndreasHeger  Ah, OK. I confess I'm not really up to scratch on databases yet so I hadn't considered all that. 

In that case, could you delete the branch and I'll make the neccessary changes to pipeline_mapping.py. 

Cheers

**Comment by AndreasHeger** [comment]
Thanks, apologies for the extra work. Unfortunately the design principles of our code base are mostly implicit, but should be made explicit.
