### ISSUE TITLE
psl2stats.py - output genomic coverage from psl formatted alignments

### ISSUE THREAD

**Issue by RadeshNMP** [CGATOxford/cgat#180]
Hello,

I wish to use only this script psl2stats.py is there a easy way to use the script or do I have to install the whole cgat package.

Please let me know what kind of output will be generated by this script.

I have installed the conda environment but am not sure how to proceed further to download the script psl2stats.py

Thank you
Radesh NMP

**Comment by sebastian-luna-valero** [comment]
Hello,

Could you please try the following steps?
```
wget https://raw.githubusercontent.com/CGATOxford/cgat/master/install-CGAT-tools.sh
install-CGAT-tools.sh --cgat-devel --location cgat-install-devel
source cgat-install-devel/conda-install/bin/activate cgat-devel
cd cgat-install-devel/cgat-code
python setup.py develop
```

After that, you should be able to run:
```
python scripts/psl2stats.py -h
```

and get a help message on how to run the script.

Best regards,
Sebastian.

**Comment by AndreasHeger** [comment]
Seems to be resolved, closing for now.
