### ISSUE TITLE
bam_vs_bed with unsorted bed files

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#181]
bam_vs_bed assumes that bed files are sorted. If they arn't then an error is caused when intersectBed is run. However, this error isn't caught, and bam_vs_bed returns without errror. This means that when run in a pipeline, the task can fail without anyone being the wiser.

**Comment by AndreasHeger** [comment]
Thanks, I have made --sort-bed the default and added an --assume-sorted option to restore the previous default behaviour.

Best wishes,
Andreas
