### ISSUE TITLE
Incorrect output from fasta2table

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#182]
Fasta to table has been output the incorrect values for it composition reporter. For example, see this output from the nosetest:

id            |nUnk|nG    |nA    |nT    |nC    |nN    |nGC   |nAT|pG      |pA      |pT      |pC      |pN      |pGC     |pAT     
--------------|----|------|------|------|------|------|------|---|--------|--------|--------|--------|--------|--------|--------
contig-0      |0   |48699 |61830 |22351 |34036 |27794 |26348 |0 |0.202218|0.307937|0.251463|0.238381|0.000000|0.440599|0.559401
contig-1000000|0   |51283 |69764 |22851 |36540 |33224 |28432 |0 |0.188778|0.301866|0.274472|0.234884|0.000000|0.423662|0.576338|
contig-2000000|0   |26036 |35011 |14668 |16666 |18345 |11368 |0  |0.240274|0.273003|0.300506|0.186217|0.000000|0.426491|0.573509
contig-3000000|0   |32149 |43973 |14496 |23591 |20382 |17653 |0  |0.190431|0.309910|0.267754|0.231904|0.000000|0.422335|0.577665
contig-4000000|0   |27964 |38693 |14994 |19076 |19617 |12970 |0  |0.224943|0.286181|0.294298|0.194578|0.000000|0.419521|0.580479
contig-5000000|0   |34816 |47180 |19061 |23070 |24110 |15755 |0  |0.232463|0.281355|0.294039|0.192144|0.000000|0.424606|0.575394
contig-6000000|0   |38650 |43370 |21653 |21112 |22258 |16997 |0  0.263997|0.257401|0.271373|0.207230|0.000000|0.471227|0.528773
total         |0   |259597|339821|130074|174091|165730|129523|0  |0.217000|0.290433|0.276485|0.216081|0.000000|0.433082|0.566918

This clearly cannot be right, since the total number of for example A's in the first row adds up to more than the number of As or Ts.

In fact, the header is being output in the wrong order. The nGC and nAT should come first. I have fixed this in the incoming pull request.

**Comment by jethrojohnson** [comment]
Hi Ian, 

Sorry, I thought I'd fixed this (see issue #177), but obviously I forgot to merge the changes. From memory, the SequenceProperties.py is also used by gtf2table.py, so I think you need to change the test files for this script as well. 

Thanks 

jethro

**Comment by IanSudbery** [comment]
Cheers Jethro, you are quite right, although this was hidden under all the other errors that Travis is currently throwing.

**Comment by IanSudbery** [comment]
Fix with PR #183
