### ISSUE TITLE
counts2counts tests

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#184]
Two of the counts2counts tests: normalise_million_counts and normalise_deseq_size_factors are failing, even on the master branch. This would appear to be due to the answers suddenly being to a different number of dp from the reference files. 

Has the version of something (R, DeSeq, pandas?) changed. Is this to do with #165 and @TomSmithCGAT 's rewrite of counts2counts.py. Should I countinue to submit commits while this is broken?

Ian
---

**Comment by TomSmithCGAT** [comment]
Hi Ian,

Are you using Python 2.7.9? We were having issues with differences in precision due to python version.

Tom

________________________________

**Comment by IanSudbery** [comment]
Hi @TomSmithCGAT yeah, 2.7.9.

**Comment by IanSudbery** [comment]
Any progess on this anyone? @TomSmithCGAT ? @sebastian-luna-valero ?

**Comment by IanSudbery** [comment]
Okay, so the baseline tests have now been updated, count2count tests passing.
