### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#187]
Hi Guys,

I'm trying to get the tools install on a students ubuntu laptop and I'm having all sorts of issues. Perhaps @sebastian-luna-valero can help?

First he tried the manual installation, and went through installing all the depedencies and then tried to install cgat but got caught by the

```
scripts/_bam2bam.pyx:137:45: Cannot convert Python object to 'BGZF *'
```

error, which it seems that is a problem for several people and normally related to pysam version. He had installed 0.8.3 so we tried downgrading it to 0.8.2.1, but that still didn't work, so he tried the conda installation.

The installation apparently went fine, but running bam2geneprofile gave the following error:

```
matt@MP-laptop:~$ cgat bam2geneprofile --help
Traceback (most recent call last):
  File "/home/matt/anaconda/bin/cgat", line 4, in <module>
    from scripts.cgat import main
ImportError: No module named scripts.cgat
```

To try and help, I install cgat-scripts into a fresh conda environment. All appeared to go well, but when I run the above command I get a different error:

```
(cgat-install-test)mb1ims@vm:~/cgat$ cgat bam2geneprofile --help
Traceback (most recent call last):
  File "/shared/conda-install/envs/cgat-install-test/bin/cgat", line 6, in <module>
    sys.exit(main())
  File "/shared/conda-install/envs/cgat-install-test/lib/python2.7/site-packages/CGAT-0.2.3-py2.7-linux-x86_64.egg/CGATScripts/cgat.py", line 126, in main
    module = imp.load_module(command, file, pathname, description)
  File "/shared/conda-install/envs/cgat-install-test/lib/python2.7/site-packages/CGAT-0.2.3-py2.7-linux-x86_64.egg/CGATScripts/bam2geneprofile.py", line 319, in <module>
    import CGAT._bam2geneprofile as _bam2geneprofile
  File "cfaidx.pxd", line 25, in init CGAT._bam2geneprofile (scripts/_bam2geneprofile.c:34731)
AttributeError: 'module' object has no attribute 'FastxFile'
```
Any ideas?

**Comment by AndreasHeger** [comment]
Thanks. I will release a new version of the CGAT script collection next week which should synchronize pysam and cgat code. In the future, I think we should always release a new CGAT script version whenever there is a new pysam.

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

For the manual installation of the CGAT scripts, please try pysam 0.8.1 while Andreas release a new version of the CGAT script collection.

Regarding Conda, I have repeated the installation both on SL 6 and Ubuntu 12.04 by following the instructions here:
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallationLinux.html#automated-installation

In both cases I did:
```
wget https://raw.github.com/CGATOxford/cgat/master/install-CGAT-tools.sh
bash install-CGAT-tools.sh --cgat-scripts --location install-cgat-dir
source install-cgat-dir/conda-install/bin/activate cgat-scripts
cgat bam2geneprofile -h
```

and it worked for me, could you please let me know what installations options did you use? and which Ubuntu version?

If your user has got sudo permissions, installing the OS dependencies (Ubuntu 12.04) could be another solution:
```
bash install-CGAT-tools.sh --install-os-packages
```

**Comment by IanSudbery** [comment]
Hi Sebastian,

To install with conda I simply did:

```
conda config --add channels cgat
conda create -n cgat-install-test python=2.7.9
source activate cgat-install-test
conda install cgat-scripts
cgat bam2geneprofile --help
```
as decribed at https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallationLinux.html#installation-with-conda

In the end we now have this working by manually installing and then cloning the lastest code version from github. 

Yours,

Ian

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

I am sorry for that, the integration with other Conda environments has not been tested thoroughly. On the other hand, I would use the following steps instead (and I will update the docs):
```
conda create -q -n cgat-env <cgat-package> gcc=4.8.3 --override-channels --channel https://conda.binstar.org/cgat --channel defaults --channel https://conda.binstar.org/r --channel https://conda.binstar.org/asmeurer
source activate cgat-env
cgat bam2geneprofile --help
```

That is done when using the script:
```
bash install-CGAT-tools.sh --cgat-scripts --location install-cgat-dir
```

I hope that helps!

Best regards,
Sebastian.
