### ISSUE TITLE
bam_vs_bed: split alignments

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#189]
bam_vs_bed currently treats alignments as starting at the start location and continuing to the end location, irrespective of if the alignment is split (/spliced). 

Adding split to the bedtools intersect call will treat the two halfs of aligment as seperate intervals, and thus will not count towards anything in the spliced out region. However, this would mean the read might be counted twice. 

Suggestions?

**Comment by AndreasHeger** [comment]
Thorough counting in an RNA-seq context will be hard without redesigning the counting from scratch.

In the meantime, we can enable the option to "--split" - and add to the documentation that this might cause one read to be counted multiple times.
