### ISSUE TITLE
cgat could not run after actived

### ISSUE THREAD

**Issue by yanzhangusa** [CGATOxford/cgat#190]
After I installed full version in google VM, I actived it and when I type cgat --help, I got following error message: 

(cgat-python)yan_zhang_sra_com@sra-yan-test:/home/yanzhangusa_gmail_com/MOUNT_POINT/isb
-cgc/cgat$ cgat --help
Traceback (most recent call last):
  File "/usr/local/bin/cgat", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: matplotlib-venn>=0.5
(cgat-python)yan_zhang_sra_com@sra-yan-test:/home/yanzhangusa_gmail_com/MOUNT_POINT/isb
-cgc/cgat$

**Comment by yanzhangusa** [comment]
reinstall using pip install cgat, got following error:

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-st
rict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-s
ecurity -fPIC -Ialignlib_src -I/usr/include/python2.7 -c alignlib_lite.cpp -o build/tem
p.linux-x86_64-2.7/alignlib_lite.o
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not
 for C++
alignlib_lite.cpp:255:32: fatal error: boost/shared_ptr.hpp: No such file or directory
 #include "boost/shared_ptr.hpp"
                                ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by sebastian-luna-valero** [comment]
Hi yanzhangusa,

Could you please post the installation steps you followed?

Best regards,
Sebastian.

**Comment by yanzhangusa** [comment]
I think it is because that I did not install biopython. After I installed biopython, it works fine.

**Comment by yanzhangusa** [comment]
great program. Like it.

**Comment by sebastian-luna-valero** [comment]
Thanks!
