### ISSUE TITLE
bam2stats memory usage

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#202]
Hi All,

DIdn't know whether to raise this as an issue here or in CGATPipelines. I'm currently processing an RNAseq experiment with nearly 200 million reads. This made bam2stats fall over, not just on the node, but also on cgat150 where there was 96GB of memory free. 

The code that is using the RAM is lines 112-124 of  _bam2stats.pyx:

```
  for fq in fastqfile:
            if fastq_nreads == 0:
                # chop off /1 or /2 as mappers usually remove these
                # suffices. Test only the first.
                name = fq.name
                if name.endswith("/1") or name.endswith("/2"): chop = -2
                
            if chop != 0:
                reads[fq.name[:chop]] = fastq_nreads
            else:
                reads[fq.name] = fastq_nreads

            fastq_nreads += 1
```

 Where a dictionary of read positions is sorted.  I know that it is not necessary to use the  fastq for the counting and this would save memory, but this is not how its coded in the mapping pipeline. 

Is there anyway to reduce the memory usage here? Or perhaps paramterise things in the mapping_pipeline. ?

Ian
---

**Comment by IanSudbery** [comment]
I split the file in half and reran it. It used 23GB for 98M reads.

**Comment by AndreasHeger** [comment]
The fastq file is necessary for the paired-end counting. If it is single end, the fastq option is not necessary and then the memory usage should be small - this could be parameterized in a pipline.

Memory usage could also be optimized by using some sort of mangling for read names - using the full read name is wasteful.

**Comment by AndreasHeger** [comment]
Hi Ian, I have imlemented the name mangling. Please let me know if it improves things. Note that there might be some inconsistencies now if two reads get the same hash, but this should be rare.
Best wishes,
Andreas
