### ISSUE TITLE
Cannot compile extensions

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#205]
I'm trying to setup cgat as a reproducible, sharable environment on our cluster.

I've installed the cgat-devel conda environment, but if I now run

```
python setup.py develop
```

or

```
python scripts/cgat_rebuild_extensions.py
```

I get the following error:

```
Traceback (most recent call last):
  File "scripts/gtf2table.py", line 477, in <module>
    import CGAT.Stats as Stats
  File "/home/mb1ims/devel/cgat/CGAT/Stats.py", line 43, in <module>
    from rpy2.robjects import r as R
  File "/home/mb1ims/.conda/envs/mb1ims/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/home/mb1ims/.conda/envs/mb1ims/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 100, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: /home/mb1ims/.conda/envs/mb1ims/lib/libreadline.so.6: undefined symbol: PC
```

This is really odd, because if I launch python and run any of import statements above, it works fine.

```
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from rpy2.rinterface._rinterface import *
>>> import rpy2.rinterface as rinterface
>>> from rpy2.robjects import r as R
>>> import CGAT.Stats as Stats
>>>
```
This is apparently a known issue with the current conda libreadline package. See
ContinuumIO/anaconda-issues#152

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

What is the OS you are running on?

Which version of GCC are you using?

Best regards,
Sebastian.

**Comment by IanSudbery** [comment]
Hi Sebastian, 
Its Scientific Linux 6.5, gcc 4.4.7. At first I thought I'd solved this problem by using the cgat-devel-lite package, but I came across it again. I got around it by uninstalling the libreadline conda package and relying on the OS library. It seems that the conda libreadline is compiled without ncurses, which rpy2 needs. See the anaconda issue linked above.

**Comment by IanSudbery** [comment]
It appears that readline is being installed by the CGATReport package, which still isn't functional - I had to clone the repository and run the setup to get it working.
