### ISSUE TITLE
rpy2 version in cgat-devel-lite conda package

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#207]
Conda package cgat-devel-lite installs rpy2 2.4.4, but running `python setup.py develop` requires 2.6, and attempts (and fails) to install it.

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

Many thanks for pointing that out.

I have updated now cgat-deve-lite, could you please try that again?

Best regards,
Sebastian.
