### ISSUE TITLE
Redirecting stdin to file in bam2fastq

### ISSUE THREAD

**Issue by izzi-13** [CGATOxford/cgat#209]
Hi,
Just to let you know, there's an issue with providing a -I option to bam2fastq: the script still seems to try to read from stdin, without warning, meaning that it appears to hang.
Thanks!
Isabel

**Comment by TomSmithCGAT** [comment]
Thanks Isabel. I'll look into this.

**Comment by TomSmithCGAT** [comment]
This should now be sorted in master. See: 94a1ce68266171a3ad17edfc4027b36557688aa3
