### ISSUE TITLE
peptides2cds removed from cgat/scripts but still in use!

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/cgat#224]
@AndreasHeger c31ff92742 removed cgat/scripts/peptides2cds.py. This scripts is still being used by CGATPipelines/CGATPipelines/PipelineGeneset.py (https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/PipelineGeneset.py#L528). Unless the script has been renamed somewhere, I'll "un-remove" it

**Comment by AndreasHeger** [comment]
Sorry, please restore.

Best wishes,
Andreas

**Comment by TomSmithCGAT** [comment]
Pull request submitted for branch Ts_restore_peptides2cds
