### ISSUE TITLE
gtf2gtf.py

### ISSUE THREAD

**Issue by AndreasHeger** [CGATOxford/cgat#226]
Potential issue:

"gtf2gtf.py is ignoring some exons where there is overlap between genes on opposite strands when merging gene models"

Could be related to sort-order of input file.

**Comment by snsansom** [comment]
For example:

zcat /ifs/mirror/annotations/mm10_ensembl78/ensembl.dir/geneset_all.gtf.gz 
       | egrep "ENSMUSG00000097924|ENSMUSG00000039578" 
       | python /ifs/devel/stephens/cgat/scripts/gtf2gtf.py --method=sort 
       | python /ifs/devel/stephens/cgat/scripts/gtf2gtf.py --method=merge-transcripts --with-utr

gives:

chr6    havana  transcript      61310855        62380264        .       +       .       gene_id "ENSMUSG00000039578"; transcript_id "ENSMUSG00000039578"; gene_biotype "protein_coding";
chr6    ensembl transcript      61175613        61180810        .       -       .       gene_id "ENSMUSG00000097924"; transcript_id "ENSMUSG00000097924"; gene_biotype "lincRNA";


but consider:
![gtf2gtf_example](https://cloud.githubusercontent.com/assets/4218768/10942320/8750953a-8307-11e5-8354-8fd03024c2be.png)

The overlapping exons are not included in the output models.

Thanks,
S.

**Comment by AndreasHeger** [comment]
Thanks, the problem is the --with-utr option, which together with the merge-transcripts method truncates transcripts at their CDS. In fact this whole arrangement was confusing. I have added two
methods:
```
--mark-utr - mark the UTR regions
--without-utr - remove UTR regions from merged transcripts
```
