### ISSUE TITLE
Expression.py replicate detection

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#24]
Currently Expression.py detects if a data set has replicates by look at the size of the smallest group. This means that in the situation of "partial replication", data is detected as replicated. However, the DESeq manual suggests treating partially replicated data as if it were replicated (using pooled variance estimation shares information across conditions anyway, so the replicated condition benefits form the the replicates in the other condition). 

I suggest the following line in Expression.py:

```
 min_per_group = R('''min(table(groups)) ''')[0]

has_replicates = min_per_group >= 2
```

become:

```
 max_per_group = R('''max(table(groups)) ''')[0]

 has_replicates = max_per_group >= 2
```

Another alternative would be to return one of three values: Unreplicated, partially replicated or replicated and deal with each case seperately (for eg enforcing pooled variance estimation), but this is probably unneccsary and the risks inherent in partially replicated data can be left to the user. 

Also when dispersion method is 'blind', Expressoin.py fails because it tries to plot dispersion estimates assuming that there are multiple dispersion estimates because it only checks that mode isn't "pooled". 

The gulity lines are:

``` python

 if dispersion_method == "pooled":
        R.png('''%sdispersion_estimates_pooled.png''' %
              (outfile_prefix))
        R.plotDispEsts(cds)
        R['dev.off']()
    else:
        dispersions = R('''ls(cds@fitInfo)''')
        for dispersion in dispersions:
            R.png('%sdispersion_estimates_%s.png' %
                  (outfile_prefix, dispersion))
        R.plotDispEsts(cds, name=dispersion)
        R['dev.off']()

```

This fails as if dispersion_method == "blind" then dispersions is empty.

I have a pull reqiuest ready for the first issue if the change is agreed.

**Comment by Acribbs** [comment]
I assume this issue can be closed, if not please reopen.
