### ISSUE TITLE
Trouble installing CGAT on BioLinux Ubuntu 14.04

### ISSUE THREAD

**Issue by alvizain786** [CGATOxford/cgat#240]
Dear Sir or Madam,

I hope this reaches you well. I am trying to install CGAT on my BioLinux Ubuntu 14.04 workstation. I was wondering what would be the best strategy on installing it as BioLinux already comes with a lot of tools. 

I have been able to install pysam and pip. 

Unfortunately, I am not able to install through the provided CGAT script as it does not allow me go through with the Ubuntu 12. version. 

I really hope to use the split gff script for my research. If someone could kindly help on how to install this. I would greatly appreciate it. 

Sincerely, 

-Zain 

I tried the following script: 

./install-CGAT-tools.sh --cgat-devel --full --location ~/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test

and it recommeneded me to contact here: 

Debugging: 
 CFLAGS:  -I/usr/include/x86_64-linux-gnu -I/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/include -L/usr/lib/x86_64-linux-gnu -L/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/lib
 CPATH:  -I/usr/include/x86_64-linux-gnu -I/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/include -L/usr/lib/x86_64-linux-gnu -L/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/lib
 C_INCLUDE_PATH: :/usr/include/x86_64-linux-gnu:/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/include
 LIBRARY_PATH: :/usr/lib/x86_64-linux-gnu:/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/lib
 LD_LIBRARY_PATH: :/usr/lib/x86_64-linux-gnu:/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/lib:/home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install/envs/cgat-devel/lib/R/lib
 PYTHONPATH: 

 There was a problem installing the code with conda. 
 Installation did not finish properly. 

 Please submit this issue via Git Hub: 
 https://github.com/CGATOxford/cgat/issues 

 Debugging: 
 CGAT_HOME: /home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test
 CONDA_INSTALL_DIR: /home/biolinux301/media/biolinux301/ab8abe44-b8f2-417c-81a5-276991c65d74/CGAT/cgat/cgat_test/conda-install
 CONDA_INSTALL_TYPE: cgat-devel

**Comment by sebastian-luna-valero** [comment]
Hello,

Indeed, we are not testing our code on Ubuntu 14.04 yet, as 12.04 is still supported. 

I will have a look though as I am interested in that as well.

Meanwhile, could you please try to run our code using docker?
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallationDocker.html

That should help you use the code without having to install the dependencies.

Best regards,
Sebastian.
