### ISSUE TITLE
bam2bam --set-nh method gives incorrect NH tag for paired end

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/cgat#241]
The --set-nh method for bam2bam should identify the number of instances of a read within a bamfile. The common use case is after alignment with BWA which doesn't add the NH tag. 

When the reads are paired end and the read names are the same (e.g no "/1" or "/2" suffixes), the _bam2bam.SetNH gives counts both paired ends as alignments of the same read and assigns NH:i:2 to both (see below). Presumably this can be resolved by querying the alignment bitwise flag which defines whether the read is first or second in the pair. I'm a bit lost as to how SetNH works though? @AndreasHeger 

> samtools view -F4 bam_mv/RS-control-3.bam |grep HISEQ:152:C80BBANXX:8:2315:12875:49546

HISEQ:152:C80BBANXX:8:2315:12875:49546  99  NC_006350   12  60  125M    =   270 383 ACCGCAGGCACTGCTGGCGAACCGTTTCGTTCAGCGATTTTTCCTGCTTGAAGATCGTCCGCAGCCACGAGGCGTCGTTGACGCGCGCCTACGCGAGCGCGCCGATCTCGTCGAGCGCCGCGCGC   CCCCCGG/EGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG   NH:i:2  MD:Z:90T34  NM:i:1  XM:i:1  AM:i:37 XG:i:0  SM:i:37 X0:i:1  X1:i:0  XT:A:U  XO:i:0

HISEQ:152:C80BBANXX:8:2315:12875:49546  147 NC_006350   270 60  125M    =   12  -383    TGAACGTGTAGACGAGATAGTCGTCCTCCGACAGCTTGAGCGGCCGGTCGATCAGCAGATAGCGCGCGAGCGTCTGGATGTAGCACGCGATCGCGGCCGCGCGGTCGACCGACAGCGGCGTGTCC   GGGGGGGGGGGGGGGGGGGGGGGBGGGGGGGEGGGGDGGGGGGGBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGGGGGGGGGGGGEGGGGGGGGGGGGGGGCCBCC   NH:i:2  MD:Z:125    NM:i:0  XM:i:0  AM:i:37 XG:i:0  SM:i:37 X0:i:1  X1:i:0  XT:A:U  XO:i:0

**Comment by MikeDMorgan** [comment]
Bump - this causes issues for pair-end ChIP-seq and ATAC-seq data.

**Comment by MikeDMorgan** [comment]
Suggested fix:
check if alignedSegment is proper paired  (AlignedSegment.is_proper_pair), if True reduce NH = NH -1, this should set both pairs as _bam2bam.SetNH does not differentiate between pairs.

**Comment by TomSmithCGAT** [comment]
Isn't it possible for a read pair to align to more than one location "properly"? I think the best solution would be for _bam2bam.SetNH() to use the "first in pair"/"second in pair" flag as well as the read name when tallying reads. This would mean a read pair with a single "proper" alignment would both get NH=1, whereas a read pair with two "proper" alignments would get NH=2 etc. I may be getting confused about the proper pair flag though?

**Comment by Acribbs** [comment]
Was this issue resolved? Can it be closed?

**Comment by TomSmithCGAT** [comment]
@MikeDMorgan - Looks like your merge resolved this? Can you confirm before we close

**Comment by MikeDMorgan** [comment]
Yep, I haven't encountered this issue since.
