### ISSUE TITLE
Error when trying to install cgat via pip

### ISSUE THREAD

**Issue by tiagobrc** [CGATOxford/cgat#246]
Here is my log error of the instalation. I already installed all dependencies. And in the end I still get this error. I read everything but could not find anything that could be solved by this.

Can someone give me a hint of what os going on? Thank you for your support.

    tiago@tiago:~$ sudo pip2.7 install cgat
    The directory '/home/tiago/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/tiago/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting cgat
      Downloading CGAT-0.2.4.tar.gz (667kB)
        100% |████████████████████████████████| 671kB 259kB/s 
    Installing collected packages: cgat
      Running setup.py install for cgat ... error
        Complete output from command /usr/bin/python2.7 -u -c "import     setuptools, tokenize;__file__='/tmp/pip-build-    SefeJR/cgat/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xd3Fyo-record/install-record.txt --single-version-externally-managed --compile:
    WARNING: depency check for UCSC tools(wigToBigWig) failed, error 127
    WARNING: depency check for bedtools(bedtools) failed, error 127
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Bioprospector.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Histogram2D.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Wiggle.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperClustal.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperDBA.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Requirements.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperCodeML.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/LCA.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/RLE.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/IOTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Glam2Scan.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Expression.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/PamMatrices.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Predictor2.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/IndexedGenome.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/ProgressBar.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Blat.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/GTF.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/ExternalList.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/BamTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Sockets.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Predictor.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Exons.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/GFF3.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Intervalls.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Iterators.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/AlignedPairs.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/VCF.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperENC.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/AString.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SaryFasta.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Bed.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Stats.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Masker.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Sra.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/GDLDraw.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Intervals.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/FastaIterator.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/GraphTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Logfile.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Diamond.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/PredictionFile.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Malis.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Fastq.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Style.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperBlastZ.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/IntervallsWeighted.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperSlr.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Motifs.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/RateEstimation.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/CSV2DB.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/MAST.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperDialign.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Metaphlan.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Biomart.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperBaseML.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Genomics.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SequenceProperties.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/GenomicIO.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperZinba.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/ProfileLibraryCompass.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Tophat.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Orthologs.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperMuscle.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/CBioPortal.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/PredictionParser.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Histogram.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Mali.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Glam2.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SVGDuplicationsWheel.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/TreeReconciliation.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperAdaptiveCAI.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Nucmer.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SequencePairProperties.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Peptides2Cds.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperExonerate.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Fasta.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/__init__.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/AGP.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperIDR.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Regions.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/MatlabTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Cluster.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SuffixArray.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Tree.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/BlatTest.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Counts.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperHmmer.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/NMF.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SVGdraw.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/ProfileLibrary.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperGblocks.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Prediction.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/MatrixTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/MaliIO.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/dictzip.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Database.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Synteny.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/BlastAlignments.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SVGTree.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/IGV.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/CSV.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperPhylip.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/IndexedFasta.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/TreeTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/SetTools.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/CorrespondenceAnalysis.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Variants.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperBl2Seq.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/GO.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Experiment.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperMACS.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/Maq.py -> build/lib.linux-x86_64-2.7/CGAT
    copying CGAT/WrapperNJTree.py -> build/lib.linux-x86_64-2.7/CGAT
    creating build/lib.linux-x86_64-2.7/CGAT/Timeseries
    copying CGAT/Timeseries/__init__.py -> build/lib.linux-x86_64-2.7/CGAT/Timeseries
    creating build/lib.linux-x86_64-2.7/CGAT/NCL
    copying CGAT/NCL/__init__.py -> build/lib.linux-x86_64-2.7/CGAT/NCL
    creating build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/split_gff.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/chain2stats.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/diff_fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gtf2gff.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2bed.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2geneprofile.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/cgat.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam_vs_bed.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fasta2table.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/diff_gtf.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/beds2beds.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2bed.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/diff_chains.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gtf2gtf.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fastq2table.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2gff.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2peakshape.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2stats.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2fastq.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gtf2tsv.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2coverage.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fastqs2fastqs.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fastq2fastq.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bed2stats.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fasta2variants.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fasta2bed.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bed2gff.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fasta2kmercontent.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/vcf2vcf.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bed2fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gtfs2tsv.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2histogram.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bed2bed.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/version.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/diff_bed.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gtf2fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/__init__.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/index_fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/diff_bam.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam_vs_gtf.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fastas2fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fasta2fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gtf2table.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam_vs_bam.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/beds2counts.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/chain2psl.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2stats.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/gff2psl.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2bam.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/fastqs2fasta.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bed2table.py -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/bam2wiggle.py -> build/lib.linux-x86_64-2.7/CGATScripts
    running egg_info
    writing requirements to CGAT.egg-info/requires.txt
    writing CGAT.egg-info/PKG-INFO
    writing top-level names to CGAT.egg-info/top_level.txt
    writing dependency_links to CGAT.egg-info/dependency_links.txt
    writing entry points to CGAT.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'CGAT.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'CGAT.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-2.7/CGAT/Components
    copying CGAT/Components/Components.cpp -> build/lib.linux-x86_64-2.7/CGAT/Components
    copying CGAT/Components/Components.pyx -> build/lib.linux-x86_64-2.7/CGAT/Components
    copying CGAT/Components/connected_components.cpp -> build/lib.linux-x86_64-2.7/CGAT/Components
    copying CGAT/Components/connected_components.h -> build/lib.linux-x86_64-2.7/CGAT/Components
    copying CGAT/Timeseries/cmetrics.pyx -> build/lib.linux-x86_64-2.7/CGAT/Timeseries
    copying CGAT/NCL/_cnestedlist.pxd -> build/lib.linux-x86_64-2.7/CGAT/NCL
    copying CGAT/NCL/cnestedlist.pyx -> build/lib.linux-x86_64-2.7/CGAT/NCL
    copying CGAT/NCL/default.h -> build/lib.linux-x86_64-2.7/CGAT/NCL
    copying CGAT/NCL/intervaldb.c -> build/lib.linux-x86_64-2.7/CGAT/NCL
    copying CGAT/NCL/intervaldb.h -> build/lib.linux-x86_64-2.7/CGAT/NCL
    copying scripts/_bam2bam.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2bam.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2bed.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2bed.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2geneprofile.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2geneprofile.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2peakshape.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2peakshape.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2stats.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bam2stats.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bams2bam.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_bams2bam.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_gtf2table.pyx -> build/lib.linux-x86_64-2.7/CGATScripts
    copying scripts/_gtf2table.pyxbld -> build/lib.linux-x86_64-2.7/CGATScripts
    running build_ext
    skipping 'CGAT/Components/Components.cpp' Cython extension (up-to-date)
    building 'CGAT.Components' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/CGAT
    creating build/temp.linux-x86_64-2.7/CGAT/Components
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c CGAT/Components/Components.cpp -o build/temp.linux-x86_64-2.7/CGAT/Components/Components.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c CGAT/Components/connected_components.cpp -o build/temp.linux-x86_64-2.7/CGAT/Components/connected_components.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/CGAT/Components/Components.o build/temp.linux-x86_64-2.7/CGAT/Components/connected_components.o -o build/lib.linux-x86_64-2.7/CGAT/Components.so
    cythoning CGAT/NCL/cnestedlist.pyx to CGAT/NCL/cnestedlist.c
    warning: CGAT/NCL/cnestedlist.pyx:106:24: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:106:28: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:382:24: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:382:28: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:262:26: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:262:30: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:346:26: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: CGAT/NCL/cnestedlist.pyx:346:30: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    building 'CGAT.NCL.cnestedlist' extension
    creating build/temp.linux-x86_64-2.7/CGAT/NCL
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c CGAT/NCL/cnestedlist.c -o build/temp.linux-x86_64-2.7/CGAT/NCL/cnestedlist.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c CGAT/NCL/intervaldb.c -o build/temp.linux-x86_64-2.7/CGAT/NCL/intervaldb.o
    CGAT/NCL/intervaldb.c: In function ‘read_imdiv’:
    CGAT/NCL/intervaldb.c:486:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
       fread(imdiv,sizeof(IntervalMap),block,ifile);
       ^
    CGAT/NCL/intervaldb.c: In function ‘read_sublist’:
    CGAT/NCL/intervaldb.c:502:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
       fread(im,sizeof(IntervalMap),subheader->len,ifile);
       ^
    CGAT/NCL/intervaldb.c: In function ‘read_subheader_block’:
    CGAT/NCL/intervaldb.c:521:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
       fread(subheader,sizeof(SublistHeader),nblock,ifile);
       ^
    CGAT/NCL/intervaldb.c: In function ‘read_binary_files’:
    CGAT/NCL/intervaldb.c:829:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
       fscanf(ifile,"%d %d %d %d %d",&n,&ntop,&div,&nlists,&nii);
       ^
    CGAT/NCL/intervaldb.c:841:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(ii,sizeof(IntervalIndex),nii,ifile);
         ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/CGAT/NCL/cnestedlist.o build/temp.linux-x86_64-2.7/CGAT/NCL/intervaldb.o -o build/lib.linux-x86_64-2.7/CGAT/NCL/cnestedlist.so
    cythoning CGAT/Timeseries/cmetrics.pyx to CGAT/Timeseries/cmetrics.c
    building 'CGAT.Timeseries.cmetrics' extension
    creating build/temp.linux-x86_64-2.7/CGAT/Timeseries
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c CGAT/Timeseries/cmetrics.c -o build/temp.linux-x86_64-2.7/CGAT/Timeseries/cmetrics.o
    In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                     from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from CGAT/Timeseries/cmetrics.c:242:
    /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                     from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from CGAT/Timeseries/cmetrics.c:242:
    /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1634:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
     _import_array(void)
     ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/CGAT/Timeseries/cmetrics.o -o build/lib.linux-x86_64-2.7/CGAT/Timeseries/cmetrics.so
    cythoning scripts/_bam2stats.pyx to scripts/_bam2stats.c
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # Alternatives to dictionary
            # 1. POSIX hash tables (hsearch,...) or trees: very slow
            # 2. custom hash implementation: worth the effort?
            # 3. Sorted list and binary search: too slow for many lookups
            reads = {}
            fastqfile = Fastqfile(filename_fastq)
                                ^
    ------------------------------------------------------------
    
    scripts/_bam2stats.pyx:110:29: undeclared name not builtin: Fastqfile
    building 'CGAT._bam2stats' extension
    creating build/temp.linux-x86_64-2.7/scripts
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE= -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/lib/python2.7/dist-packages/pysam -I/usr/local/lib/python2.7/dist-packages/pysam/include/htslib -I/usr/local/lib/python2.7/dist-packages/pysam/include/samtools -I/usr/include/python2.7 -c scripts/_bam2stats.c -o build/temp.linux-x86_64-2.7/scripts/_bam2stats.o
    scripts/_bam2stats.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
        ----------------------------------------
    Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SefeJR/cgat/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xd3Fyo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-SefeJR/cgat

**Comment by IanSudbery** [comment]
This is the same problem as #244.
The problem is that the pysam 00.8.4 is being installed, but the code on pypy hasn't been updated to account for that. 
I suggest that you either use the conda installation method, or clone the code from github and install manually. 

From an appropriate directory:
```
git clone git@github.com:CGATOxford/cgat.git
cd cgat
python setup.py install
```

You can delete the downloaded directory afterwards. 

@sebastian-luna-valero Anything to add?

**Comment by IanSudbery** [comment]
Over on #244 Brian found that 

```
pip install git+https://github.com/CGATOxford/
```

after install the dependencies did the job.

**Comment by sebastian-luna-valero** [comment]
Hi both,

Looks good to me, thanks @IanSudbery 

Please find the documentation here:
https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallation.html#cgat-code-clean-installation

Either Conda, Docker or Vagrant might help you get started with the CGAT code.

Best regards,
Sebastian.

**Comment by IanSudbery** [comment]
This issue has been consolidated with several others on issue #252, please see there for further developments.
