### ISSUE TITLE
Extend BED interval to specific size

### ISSUE THREAD

**Issue by MikeDMorgan** [CGATOxford/cgat#247]
Currently bedtools features and bed2bed.py do not have a feature to extend/clip intervals to a specific size.  This may be a requirement for some third-party tools, for instance the MEME-suite of programs expect sequences to be of the same length.

Suggestion:  allow a --set-interval size option that iteratively pads and/or clips intervals to the specific length.

Possible solutions:  

- Take the size as the distance from the current centre of the interval and extend/clip symmetrically to get the appropriate size
- Allow assymetric padding/clipping in either 5' or 3' direction to achieve the desired interval length

Need to account for contig size to prevent extension off the end of the chromosome.

Other suggestions/potential bug catches are encouraged.

**Comment by AndreasHeger** [comment]
Hi Mike, this makes sense, but could this be solved through some bedtools /awk combination, i.e., select midpoint of each interval and then use bedtools slop?

**Comment by MikeDMorgan** [comment]
Thanks Andreas, I agree about the midpoint intervals.  I'm struggling to think of an awk/bedtools combo that would allow one to extend only in one direction and retain a specific size interval.

**Comment by AndreasHeger** [comment]
@MikeDMorgan, I probably don't have the full picture, but bedtools slop can extend upstream or downstream only depending on strand (-l -r -s options)?

**Comment by MikeDMorgan** [comment]
Thinking about it, I'm not sure you even need to use bedtools, maybe just an awk 1-liner would do it.  Something like:

For 3' slopping:
cat mybed.bed | awk '$2 = $3 - 500'

For 5' slopping:
cat mybed.bed | awk '$3 = $2 + 500'

**Comment by AndreasHeger** [comment]
except you need to be careful at chromosome boundaries, which is the extra bit that bedtools slop does.

For motif search you might also worry about gaps/N's in the sequence?

**Comment by MikeDMorgan** [comment]
Revisitng this.  It turns out the documentation for bedtools slop is inaccurate.  It states that -l _removes_ from the start of the interval, when it clearly just extends _or_ subtracts depending on the usage.
