### ISSUE TITLE
Code version on PyPy not compatible with listed dependencies

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#252]
This is issue combines the several others with the same problem ( #250, #246, #244, #156). This is that the version of the code on PyPy, which was is the last official release, doesn't work with the dependencies listed in the documentation, specifically pysam 0.8.4.

Although deep inside the documentation it is suggested that installation with pip is no longer support, the front page encourages people to install this way. 

There are several solutions to this problem: 

1.  Release a hotfix to the the PyPy code allowing it to work with pysam 0.8.4
2. Change the documentation/requirements.txt so that pysam 0.8.3 is installed not pysam 0.8.4, flag up incompatibility with pysam 0.8.4 on the released versions as a known issue.
3. Stop advising people to use pip to install the code. 

Personally I think that 1 would be ideal, as lots of people would like to use cgat via pip to integrate with their current workflow without forever having to activate and deactivate environments. But I can see that even if we document things correctly, this is still going to cause headaches. 

Altering things on PyPy is not something I can do.

**Comment by sebastian-luna-valero** [comment]
I agree, we should update the code on PyPI.

I have created an account but I do not have permissions to update the CGAT code. I will ask for help.

**Comment by sebastian-luna-valero** [comment]
A new version of the code has been uploaded to PyPI so that should hopefully solve these problems.
