### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by tallulandrews** [CGATOxford/cgat#256]
I'm trying to install a copy of cgat locally for myself on a shared computing cluster ie: 
pip install -install-option="--prefix=~/PythonPackages" cgat

However I get the following error (the same occurs if I follow the instructions for manual installation) :

"Downloading/unpacking cgat
  Running setup.py egg_info for package cgat
    Traceback (most recent call last):
      File "< string >", line 14, in <module>
      File "/nfs/users/nfs_t/ta6/PythonPackages/cgat-python/build/cgat/setup.py", line 250, in < module >
        pysam.get_libraries()]
    AttributeError: 'module' object has no attribute 'get_libraries'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "< string >", line 14, in <module>

  File "/nfs/users/nfs_t/ta6/PythonPackages/cgat-python/build/cgat/setup.py", line 250, in < module >
   pysam.get_libraries()]

AttributeError: 'module' object has no attribute 'get_libraries'

I've updated Pysam but that did not resolve the issue. 

Tallulah

**Comment by sebastian-luna-valero** [comment]
Hi Tallulah,

What's the output of these commands:
```
which python
echo $PYTHONPATH
which pip
pip list | grep pysam
python -c "import pysam; print pysam.__version__"
python -c "import pysam; print pysam.__file__"
```

Best regards,
Sebastian.

**Comment by tallulandrews** [comment]
>which python
/nfs/users/nfs_t/ta6/PythonPackages/cgat-python/bin/python
>echo $PYTHONPATH
/nfs/users/nfs_t/ta6/.local/lib/python2.7/site-packages/:/nfs/users/nfs_t/ta6/PythonPackages:/nfs/users/nfs_t/ta6/RNASeqPipeline/software:/nfs/users/nfs_t/ta6/RNASeqPipeline/software/usr/local/lib/python2.7/dist-packages/:/usr/local/lib/python2.7/dist-packages/:/nfs/users/nfs_t/ta6/PythonPackages/lib/python2.7/site-packages/:/nfs/users/nfs_t/ta6/.local/lib/python2.7/site-packages/:/nfs/users/nfs_t/ta6/PythonPackages:/nfs/users/nfs_t/ta6/RNASeqPipeline/software:/nfs/users/nfs_t/ta6/RNASeqPipeline/software/usr/local/lib/python2.7/dist-packages/:/usr/local/lib/python2.7/dist-packages/:/nfs/users/nfs_t/ta6/PythonPackages/lib/python2.7/site-packages/:/nfs/users/nfs_t/ta6/PythonPackages:/nfs/users/nfs_t/ta6/RNASeqPipeline/software:/nfs/users/nfs_t/ta6/RNASeqPipeline/software/usr/local/lib/python2.7/dist-packages/:/usr/local/lib/python2.7/dist-packages/:/nfs/users/nfs_t/ta6/PythonPackages/lib/python2.7/site-packages/:
 >which pip
/nfs/users/nfs_t/ta6/PythonPackages/cgat-python/bin/pip
>pip list | grep pysam
Usage: pip COMMAND [OPTIONS]

pip: error: No command by the name pip list
  (maybe you meant "pip install list")
>python -c "import pysam; print pysam.__version__"
0.7.5
>python -c "import pysam; print pysam.__file__"
/nfs/users/nfs_t/ta6/RNASeqPipeline/software/usr/local/lib/python2.7/dist-packages/pysam/__init__.pyc

**Comment by sebastian-luna-valero** [comment]
Hi,

I would try upgrading pysam first:
```
pip install pysam==0.8.4
```

and check that you are running that version (0.8.4):
```
python -c "import pysam; print pysam.__version__"
```

Then, try reinstalling the cgat code.

If that option does not work either, I would try:
```
wget https://raw.github.com/CGATOxford/cgat/master/install-CGAT-tools.sh
bash install-CGAT-tools.sh --cgat-scripts --location /nfs/users/nfs_t/ta6/PythonPackages/cgat-conda
```

Best regards,
Sebastian.
