### ISSUE TITLE
SRA extract fails for SOLID data

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/cgat#274]
When a .sra file contains SOLID data, fastq dump extracts a single fastq instead of a fasta and separate quality file as required for some downstream tools (e.g Tophat2). Propose adding option to use abi-dump to SRA.py and auto-detecting datatype in SRA.peek()

**Comment by TomSmithCGAT** [comment]
Could someone sanity check the commits on branch https://github.com/CGATOxford/cgat/tree/TS-handleSolidDataFromSra please.

**Comment by Acribbs** [comment]
@TomSmithCGAT Can I close this?

**Comment by TomSmithCGAT** [comment]
Yeah, looks like this branch was merged a while ago (#281). Cheers
