### ISSUE TITLE
gtf2gtf.py failing tests locally

### ISSUE THREAD

**Issue by nickilott** [CGATOxford/cgat#289]
As the title suggests I have come across gtf2gtf.py failing multiple tests locally. They are concerned with the "intersect_transcripts_with_utr" tests. I'm not sure why this would be as the master appears to be passing and I have made no changes to this script locally?

**Comment by sebastian-luna-valero** [comment]
Hi Nick,

Getting errors here as well. Digging a bit deeper, when I manually run the `rename_gene` test, the first line of the reference file is:
```
chr19	protein_coding	exon	281043	281537	.	-	.	exon_number "6"; gene_id "ENSG000001419341"; exon_id "ENSE00000951311"; transcript_name "PPAP2C-001"; gene_biotype "protein_coding"; transcript_id "ENST00000269812"; gene_name "PPAP2C";
```

whereas the first line of the gtf2gtf output is:
```
chr19	protein_coding	exon	281043	281537	.	-	.	gene_id "ENSG000001419341"; transcript_id "ENST00000269812"; exon_number "6"; gene_name "PPAP2C"; gene_biotype "protein_coding"; transcript_name "PPAP2C-001"; exon_id "ENSE00000951311";
```

So the information is the same but the order of the columns are different which causes the checksum to be different, and thus the error.

However, I do not know why this is happening provided that the script and data are exactly the same locally and on github/travis. The only difference must be in the software environment but I can't think of any specific reason.

Let's see if anyone else is able to help.

**Comment by AndreasHeger** [comment]
Hi all,

this is a pysam issue. I fixed a bug that preserves the order of GTF 
fields. I think this is pysam 0.9.4.

Best wishes,
Andreas

**Comment by nickilott** [comment]
Sorry, maybe I'm not understanding. So this means the reference in the tests is incorrect and needs replacing? Did you mean pysam 0.9.1.4 (this is what I have installed)?

**Comment by sebastian-luna-valero** [comment]
Many thanks, Andreas!

That explains it!

Travis/Conda is using pysam 0.8.4 (that will be fixed once we merge the master with the `AH-Python3Compatibility` branch) while locally we are using pysam 0.9.1

Once that has been done, you are right Nick, we'll have to update the reference files in the tests.

Let's leave this open as a reminder.

**Comment by AndreasHeger** [comment]
Thanks, I already changed it in the py3 branch.

Best wishes,
Andreas

**Comment by sebastian-luna-valero** [comment]
I have had the gtf2gtf test errors with the latest pysam on branch `NEI-debugLCA` here:
https://travis-ci.org/CGATOxford/cgat/jobs/161307641#L1790
https://travis-ci.org/CGATOxford/cgat/jobs/161307656#L1929

Just to let you know that I have updated the test files for gtf2gtf to pass the tests on that branch, and seems to work:
https://travis-ci.org/CGATOxford/cgat/builds/161336590

So I am going to merge with master those changes.
