### ISSUE TITLE
Issues with deseq2ParseResults in Expression.py

### ISSUE THREAD

**Issue by nickilott** [CGATOxford/cgat#290]
deseq2ParseResults does not process results correctly when there are more than two groups in the design file i.e. this code is in the runDESeq2 function for combining multiple contrasts

``` python
for combination in contrasts:
        variable, control, treatment = combination
        ...
        df_out = deseq2ParseResults(fdr, vsd=False)
```

deseq2ParseResults only takes the first two conditions from the global "groups" variable and therefore when it comes to labelling treatment_name and control_name in the outputs it is always the same two from the design file reagardless of the values of control and treatment in the above statement.

I would suggest that treatment_name and control_name are specified as arguments to deseq2ParseResults so that the correct labels and values are used in output

``` python
def deseq2ParseResults(treatment_name, control_name, fdr, vsd=False):
```

with the following resulting changes to the code

``` python
R('''g = unique(groups[groups == "%s" | groups == "%s"])''' % (treatment_name, control_name))
R('''g1 = which(groups == g[1])''')
R('''g2 = which(groups == g[2])''')
R('''res2['treatment_name'] = g[1]''')
R('''res2['treatment_mean'] = rowMeans(normalcounts[, g1])''')
R('''res2['treatment_std'] = apply(normalcounts[, g1], 1, sd)''')
R('''res2['control_name'] =g[2]''')
R('''res2['control_mean'] = rowMeans(normalcounts[,g2])''')
R('''res2['control_std'] = apply(normalcounts[, g2], 1, sd)''')
```

**Comment by sebastian-luna-valero** [comment]
Many thanks @nickilott 

Could you please open a proper pull request so we all can review changes?

**Comment by nickilott** [comment]
Yes will do this now. Thanks

**Comment by Acribbs** [comment]
The Expression.py code has gone through significant changes since this issue. I will close it but please reopen if you think it necessary
