### ISSUE TITLE
Conda installation broken

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#301]
Hi All,

Conda installation isn't working for us at the moment. If I do:

```
conda create -n test python=2.7
source activate test
conda install cgat-devel
```

The installation gets stuck at 

```
Solving package specifications: .............
```
CPU usage sits at 100% for as long as I let it - i've left it up to 8 hours with no progress. I've also tried it on three different machines now, one with Ubuntu, one on scientific linux 6 and one on CentOS 7.

I'll post over at conda as well to see if they have anything to say..

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

Sorry for that, I am actually working on a new conda package.

Are you using Miniconda for Py27 or Py35?

Meanwhile, could you please try:

```
wget https://raw.githubusercontent.com/CGATOxford/cgat/master/install-CGAT-tools.sh
bash install-CGAT-tools.sh --cgat-devel --location /full/path/to/location

# this should be equivalent to:

conda create -q -n test cgat-devel python=2.7 --override-channels --channel https://conda.anaconda.org/cgat --channel defaults --channel https://conda.anaconda.org/conda-forge --channel https://conda.anaconda.org/r --channel https://conda.anaconda.org/bioconda --yes

```

which is what I use here:
https://github.com/CGATOxford/cgat/blob/master/install-CGAT-tools.sh#L287

The dependency resolution algorithm in Conda goes crazy from time to time when new dependencies are added to the channels that you are subscribed to. 

I hope that helps.

Best regards,
Sebastian

**Comment by IanSudbery** [comment]
Hi Sebastian,

This worked for a while, but now this command hangs indefinitely, while not overriding the channels doesn't. However we get some funny versions of things install if we don't override channels: an old pysam version and an old sphinx version. Currently we install cgat-dev without overriding channels, and then uninstall and reinstall sphinx and pysam. This time we do override channels. 

In addition the install routine for both CGATReport and sphinx is leaving us with broken console_scripts:

```
Traceback (most recent call last):
  File "/home/mb1ims/.conda/envs/sharc/bin/sphinx-build", line 9, in <module>
    load_entry_point('Sphinx==1.3b1', 'console_scripts', 'sphinx-build')()
  File "/usr/local/packages/apps/conda/pkgs/setuptools-27.2.0-py27_0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/packages/apps/conda/pkgs/setuptools-27.2.0-py27_0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2597, in load_entry_point
ImportError: Entry point ('console_scripts', 'sphinx-build') not found
```

This works fine after we have uninstalled and reinstall `sphinx` from `defaults` rather than `cgat`. 

We get the same problem with `CGATReport`. However, an uninstall and reinstall doesn't fix here. If we clone the most up-to-date version from andreas' repo, it has requirements that aren't installed (e.g. ggplot>=0.9.8) , we have to:

delete all traces of `CGATReport` from `conda/envs/my_env/lib/python2.7/site-packages`

clone the v0.3 tag from the `CGATReport` repo and manually install.  We also need to manually update the seaborn dependency. 

Who packages CGATReport? Is that you or Andreas?

Ian
---

**Comment by sebastian-luna-valero** [comment]
Hi Ian,

Sorry to hear that.

I am moving away from our own `cgat` channel and adopting `bioconda` and `conda-forge` channels instead.

Could you please try:
```
conda create -q -n cgat-scripts-devel cgat-scripts-devel --override-channels --channel bioconda --channel r --channel defaults --channel conda-forge --yes
```

Please note that I am also updating the package names (i.e. `cgat-scripts-devel` replaces `cgat-devel`, I will give more details soon).

The command above should pick up the correct python version that you have installed.

Please let me know whether it works.

Best regards,
Sebastian

**Comment by IanSudbery** [comment]
@sebastian-luna-valero 

I tried the new conda installation instruction and we ran into a problem were we got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mba15om/.conda/envs/sharc/lib/python2.7/site-packages/rpy2/tests.py", line 23, in <module>
    import rpy2.tests_rpy_classic
  File "/home/mba15om/.conda/envs/sharc/lib/python2.7/site-packages/rpy2/tests_rpy_classic.py", line 3, in <module>
    import rpy2.rpy_classic as rpy
  File "/home/mba15om/.conda/envs/sharc/lib/python2.7/site-packages/rpy2/rpy_classic.py", line 5, in <module>
    import rpy2.rinterface as ri
  File "/home/mba15om/.conda/envs/sharc/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 99, in <module>
    from rpy2.rinterface._rinterface import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

Comparing the offending environment to my environment i saw that the version of rpy2 was older (2.7.8 was installed on the new environment, my environment had rpy2 2.8.5) . upgrading to rpy2 2.8.5 solved the issue.

**Comment by sebastian-luna-valero** [comment]
Thanks @IanSudbery 

Indeed, I need to update the conda package (bioconda has recently [changed](https://github.com/bioconda/bioconda-recipes/pull/4972)). In the meantime the work around is to enforce R-3.3.1 for the installation (please see https://github.com/CGATOxford/cgat/commit/b179bf5e6562f56cf579feaad9be1f9a676f77bd)

**Comment by IanSudbery** [comment]
Thanks

**Comment by Acribbs** [comment]
Since this is old and sebastian has a new conda installation I will close this
