### ISSUE TITLE
Deprecated Functions in Annotations_Pipeline & New Ensembl Notation

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/cgat#317]
I have rerun the annotations pipeline on the newest annotations.
There are some new changes in the recent ensembl releases: Whereas the GTF still has "ENSPXXX" notation, the .pep. file and the .cdna. file now have transcript/protein notation with a suffix: "ENSPXXX.1" etc. Because there are multiple steps at which these tables are combined we need to find a solution to this:
Options:
- Remove ".1" suffix when loading these databases (I have implemented this)
- Create Additional Columns

While looking at this I found another error that used to fail the pipeline. Pipeline_annotations relies on peptide2cdna methods, which in turn rely on an ancient library written by Adnreas: alignment_light. The library still exists but has been massively rewritten. Given that the cdna/peptide functionality has not been used I have taken the entirety of these function and methods out, as they need to be rewritten from scratch if at all needed (what was its purpose?). The cdna fasta is now made from ensembl cdna data only.

see Pull Request #318 
Also See Pull Request in CGATPipelines CGATOxford/CGATPipelines#312

**Comment by AndreasHeger** [comment]
Hi @jscaber , thanks, taking these out is fine - they were mostly useful for gene-prediction tasks and comparative genomics, not so much our focus now.

**Comment by sebastian-luna-valero** [comment]
Many thanks @jscaber and @AndreasHeger !
