### ISSUE TITLE
gtf2gtf sorting

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/cgat#328]
I have  have noticed that sorting by gene and transcript requires each of the entries to have both a "transcript_id" and a "gene_id". This can be a bit frustrating. For example the annotations pipeline requires all genes to be grouped first into gene_ids and then transcript_ids, but the sorting fails because feature == "gene"  entries do not have a transcript_id.

I wonder whether the sorting should be able to handle this?

**Comment by IanSudbery** [comment]
A GTF file that has entries without a transcript_id field is not a valid
GTF.



See: http://mblab.wustl.edu/GTF22.html



GTF files do not have gene entries. Are you sure you are not working with a
GFF3 file?

**Comment by jscaber** [comment]
Yes, correct - it was labeled as GTF but is probably a GFF.
No need for such sorting then. Closed.
