### ISSUE TITLE
annotations_pipeline: gene_biotype vs gene_type

### ISSUE THREAD

**Issue by jscaber** [CGATOxford/cgat#329]
Should the annotations pipeline be able to handle both gtfs with a gene_type and gene_biotype annotation? At the moment only gene_biotype is supported. Gene_type is ignored and the biotype is fetched from the source column instead.

At the moment the following code exists in gtf2gtf:
`if "gene_biotype" not in gff.attributes:
gff.setAttribute("gene_biotype", gff.source)`

Should we be able to handle both formats or is this unlikely to bother anyone in the future?
ENCODE uses "gene_type".

**Comment by sebastian-luna-valero** [comment]
Hi @jscaber 

Have you had a look at https://github.com/CGATOxford/CGATPipelines/pull/323

**Comment by Acribbs** [comment]
I think this should be solved with the new pipeline. If im wrong please open it again.
