### ISSUE TITLE
GTF.py - issue with attributes fields in GTF-Entry class

### ISSUE THREAD

**Issue by kathrinjansen** [CGATOxford/cgat#350]
Hi all,
Should the line below in GTF.py (line 840) maybe be changed to the code suggested?
It looks like this is currently not keeping the last item in the attributes field if the final “;” of the line does not have a space. The new code below should take care of both “;” and “; “ at the end of the line.
Best wishes,
Kathrin

(line 840 in GTF.py)
`fields = [x.strip() for x in attributes.split("; ")[:-1]]`

suggested replacement:
`fields = [x.strip() for x in attributes[:attributes.rfind(";")].split("; ")]`

**Comment by AndreasHeger** [comment]
Many thanks, changed and committed!
