### ISSUE TITLE
PipelineGWAS.py

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/cgat#352]
Hi @MikeDMorgan 

Should I move `PipelineGWAS.py` from the scripts repository:
https://github.com/CGATOxford/cgat/blob/master/CGAT/PipelineGWAS.py

to the pipelines repository?
https://github.com/CGATOxford/CGATPipelines/tree/master/CGATPipelines

Best regards,
Sebastian

**Comment by MikeDMorgan** [comment]
Hi Sebastian,
This module file started life as the pipeline module library, but it quickly evolved into a library for more generic analyses/handling large-scale genetic data.  It should be renamed to just `GWAS.py`, but I never got around to it.

**Comment by sebastian-luna-valero** [comment]
Solved in https://github.com/CGATOxford/cgat/pull/354
