### ISSUE TITLE
bits_test call in bed_vs_bed.py

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/cgat#353]
Hi everyone,

The `bed_vs_bed.py` script says:

> This script is a wrapper around bits_test. It splits one bedfile by name and computes the overlap of intervals in the first :term:`bed` file against the other.

and contains a [call](https://github.com/CGATOxford/cgat/blob/master/CGAT/scripts/bed_vs_bed.py#L88) to an external program called `bits_test`.

Could somebody please point me to this external program?

Google takes me to [bits](https://github.com/arq5x/bits), but the CUDA requirement makes me doubt.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Will ignore this dependency in the conda environment.

Feel free to reopen and add your comments.

**Comment by AndreasHeger** [comment]
This is the correct bits, there is a non-cuda version as well.

**Comment by Acribbs** [comment]
@sebastian-luna-valero can this be closed?
