### ISSUE TITLE
asGFF3() pysam error with gtf2gtf.py

### ISSUE THREAD

**Issue by Acribbs** [CGATOxford/cgat#356]
@AndreasHeger I have been working with pysam 0.11.2.2 and trying to run the following command:

cat /ifs/projects/adam/pipeline_gtf_test/data/test/test_gtf_subset.dir/test.gtf     | awk '$3 == "exon"'     | grep "transcript_id"     | cgat gtf2gtf     --method=sort     --sort-order=contig+gene     --log=ensembl.dir/geneset_flat.gtf.gz.log  2>/dev/null   | cgat gtf2gtf     --method=merge-exons --use-gene-id     --log=ensembl.dir/geneset_flat.gtf.gz.log

I get the following error:

  `File "/ifs/devel/adamc/py35-v1/conda/bin/cgat", line 11, in <module>
    load_entry_point('CGAT', 'console_scripts', 'cgat')()
  File "/ifs/devel/adamc/py35-v1/cgat/CGAT/cgat.py", line 132, in main
    module.main(sys.argv)
  File "/ifs/devel/adamc/py35-v1/cgat/CGAT/scripts/gtf2gtf.py", line 1393, in main
    result.extend(output_ranges(r, gffs, biotype, options.use_geneid))
  File "/ifs/devel/adamc/py35-v1/cgat/CGAT/scripts/gtf2gtf.py", line 1338, in output_ranges
    entry.copy(gffs[0])
  File "/ifs/devel/adamc/py35-v1/cgat/CGAT/GTF.py", line 998, in copy
    self.attributes = collections.OrderedDict(other.asDict().items())
  File "pysam/libctabixproxies.pyx", line 456, in pysam.libctabixproxies.GTFProxy.asDict (pysam/libctabixproxies.c:7873)
  File "pysam/libctabixproxies.pyx", line 622, in pysam.libctabixproxies.GTFProxy.__getattr__ (pysam/libctabixproxies.c:11835)
KeyError: 'attribute_iterator'`

However, when I revert back to pysam 0.11.1 this error disappears. I think there must be an issue with the key error in the __getattr__ function in libctabixproxies.pyx of pysam in 0.11.2.2.

I dont know if this has been fixed in pysam 0.12.0.1, but unfortunately I am unable to update the conda installation because of the following problems:

First, the package is listed as htslib1.5_0 and not a python version-
`0.12.0.1            htslib1.5_0  bioconda`

Second, the error is as follows - 
 `UnsatisfiableError: The following specifications were found to be in conflict:
  - pysam 0.12.0.1* -> python 2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
`
Unfortunately because of the lack of asGFF3 functionality in pysam 0.11.1 I am unable to make tests on my pipeline and because of the error in pysam 0.11.2.2 I cant run gtf2gtf and complete the testing.

Thanks,
Adam

**Comment by AndreasHeger** [comment]
I think it should be fixed in the new version. Strange the install does not work.

**Comment by Acribbs** [comment]
This has been fixed with the pysam conda update. Thanks for your help @AndreasHeger
