### ISSUE TITLE
gff2fasta gives wrong sequence if samtools index is used

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#378]
gff2fasta needs and indexed fasta file to get the sequence from. It gets this using `CGAT.IndexedFasta`. 

`CGAT.IndexedFasta` will accept either a `cgat` or `samtools` index for the fasta, however, the sequence output is only correct if the index is a `cgat` index, not if it is a `samtools` index.

I am thinking that almost all of the CGATPipelines that use gff2fasta are going to be pulling from directories with samtools indexes on the fastas. 

Several pipelines have "/ifs/mirror/genomes/faidx" set as the genome_dir and even those that don't often refer to genomes with the extension ".fa" (the cgat indexed genomes in /ifs/mirror/genomes/plain use the extension .fasta"). I have in particular noticed that all the alignement free stuff from rnaseqdiffexpression is wrong because it uses a geneset gtf to generate the salmon/kalisto index and because it assumes a ".fa" suffix, it is assume a genome from the samtools indexed directories. 

Note this is not easy to spot because although the salmon logs do have a mapping rate, we don't pull that out and display it anywhere in the report. (my mapping rate on a recent run was 35%,)

Take for example the following two commands:

```
cgat gff2fasta --genome-file=/ifs/mirror/genomes/plain/hg19.fasta --is-gtf -S test1fa.gz --fold-at=60 -I /ifs/projects/proj028/annotations/ensembl.dir/geneset_exons.gtf.gz

cgat gff2fasta --genome-file=/ifs/mirror/genomes/faidx/hg19.fa --is-gtf -S test2.fa.gz --fold-at=60 -I /ifs/projects/proj028/annotations/ensembl.dir/geneset_exons.gtf.gz
```
They should give the same output file, but if you compare the sequence of ENST00000327669 in test1 and test2 we see they are not the same:

```
$ zgrep -A 2 ENST00000327669 test1.fa.gz 
>ENST00000327669 chr2:-:45439-46385;38813-41627
ATGCGCGCCCTGGCGGCCCTGAGCGCGCCCCCGAACGAGCGGCTCCTTCCCCGGGACCCC
GCGGCTACCCGGGACCCCGACGCCGCGCGGCCGGCGCGCAGGAGCGCAGTGGAGAGGCTG

$  zgrep -A 2 ENST00000327669 test2.fa.gz 
>ENST00000327669 chr2:-:45439-46385;38813-41627
CTCCAGCGTCGAGAGCCTGGGGCAGCCTTCCTGAGCCTGGGTTTCCTCGACTCTCAGGTT
CTTCTCTCTCCGAAATCCCATGCCACACCATTGGTTTAGATTTGCATATTATGATGGTGG
```

If we look in the original ENSEMBL fasta, we can see that the first of these is correct

```
$ zgrep -A 2 ENST00000327669 /ifs/mirror/ensembl/hg19/Homo_sapiens.GRCh37.75.cdna.all.fa.gz 
>ENST00000327669 cdna:known chromosome:GRCh37:2:38814:46385:-1 gene:ENSG00000184731 gene_biotype:protein_coding transcript_biotype:protein_coding
ATGCGCGCCCTGGCGGCCCTGAGCGCGCCCCCGAACGAGCGGCTCCTTCCCCGGGACCCC
GCGGCTACCCGGGACCCCGACGCCGCGCGGCCGGCGCGCAGGAGCGCAGTGGAGAGGCTG
```

At first I thought it might be the genes on the minus strand that were different, but although all the differences I've seen are on the minus strand, not all minus strand genes seem to be different.

**Comment by AndreasHeger** [comment]
Thanks, I will look into this and fix.

**Comment by AndreasHeger** [comment]
Hi @IanSudbery , I think we have an issue with the indices:
```
  ll /ifs/mirror/genomes/faidx/hg19.fa*
-rw-rw-r-- 1 andreas usersfgu 3.0G Jun 28  2016 /ifs/mirror/genomes/faidx/hg19.fa
-rw-rw-r-- 1 andreas usersfgu 3.5K Jan 12  2011 /ifs/mirror/genomes/faidx/hg19.fa.fai
(cgat-s) andreas@cgath2[0]: /ifs/devel/andreas/cgat/t >
  ll /ifs/mirror/genomes/index/hg19.fa*
-rw-rw-r-- 1 michaelm usersfgu 3.0G Jun 28  2016 /ifs/mirror/genomes/index/hg19.fa
-rw-rw-r-- 1 andreas  usersfgu  785 Jun 28  2016 /ifs/mirror/genomes/index/hg19.fa.fai
```
As you can see, one index is older than the actual file and the other index is truncated. I reindexed and now I get the same result.

**Comment by AndreasHeger** [comment]
Closing this for now, but reopen if this was not the issue.
