### ISSUE TITLE
gtf2gtf endless processing

### ISSUE THREAD

**Issue by sandobits** [CGATOxford/cgat#398]
Hello.
I'm having an issue on which I run the gtf2gtf script, the process starts but never ends and the 'top' task manager also showed no signs of any processes apparently derived from the script. I left it idle for about half an hour to absolutely no difference in either the task manager or the running script itself.
I have some screenshots of the commands and the behaviour.

![run-cgat-gtf2gtf-issue-screenshot1-running-process-forever_2018-09-01_11-28-11](https://user-images.githubusercontent.com/31490653/44965330-5166e900-af0b-11e8-8287-cfced5479f56.png)
![run-cgat-gtf2gtf-issue-screenshot2-process-canceled_2018-09-02_11-21-13](https://user-images.githubusercontent.com/31490653/44965331-5166e900-af0b-11e8-82fb-6d699cb50d89.png)
![run-cgat-gtf2gtf-issue-screenshot3-reading-taskmanager_2018-09-01_11-28-11](https://user-images.githubusercontent.com/31490653/44965334-51ff7f80-af0b-11e8-883b-94dd192c0825.png)

**Comment by IanSudbery** [comment]
Hi,

The script is waiting for input. This is because gtf2gtf takes its input
from the stdin. If you wish to direct a file in, then use the option
--stdin/-I before the name of the input file.

>
>
