### ISSUE TITLE
pip install 'bx-python==0.7.3' - exit status 1

### ISSUE THREAD

**Issue by sandobits** [CGATOxford/cgat#399]
I had CGAT installed on my personal machine running Linux Mint 18.3, and worked fine.
I tried installing it on the laboratory computer, which runs Ubuntu 16.04, but I got the following error message:

> Command "/home/mfl/cgat-install/conda-install/envs/cgat-s/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-acpztonj/bx-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-w4j2obdu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-acpztonj/bx-python/
> 
> ########################################################## 
> 
 > An error occurred in:
> 
>  - line number: 275
> - exit status: 1
>  - command: pip install 'bx-python==0.7.3'
> 
>  The script will abort now. User input was: 
> 
>  ./install-CGAT-tools.sh --production
> 
>  Please copy and paste this error and report it via Git Hub: 
>  https://github.com/CGATOxford/cgat/issues 
> 
>  Debugging: 
>  CFLAGS: 
>  CPATH: 
>  C_INCLUDE_PATH: 
>  CPLUS_INCLUDE_PATH: 
>  LIBRARY_PATH: 
>  LD_LIBRARY_PATH: 
>  CGAT_HOME: /home/mfl/cgat-install
>  CONDA_INSTALL_DIR: /home/mfl/cgat-install/conda-install
>  CONDA_INSTALL_TYPE: cgat-scripts
>  CONDA_INSTALL_ENV: cgat-s
>  PYTHONPATH: 
>  INSTALL_BRANCH: master
> RELEASE: 
>  CODE_DOWNLOAD_TYPE: 0
> 
>  ########################################################## 

I do not know any other variables involved in the installation process other than the operating system and hardware configuration.

**Comment by Acribbs** [comment]
Hi,

We are actually in the process of porting most of our code and refactoring to https://github.com/cgat-developers/cgat-apps. I think we have removed the bx-python dependancy (from memory pip install bx-python does not install some shared libraries and can have dependancy issues) so you may want to consider trying to install this new code.
