### ISSUE TITLE
CGAT fails to install using conda

### ISSUE THREAD

**Issue by ghost** [CGATOxford/cgat#400]
I have been trying to install CGAT using conda but I haven't been able. In my last attempt, I used the recommended steps in the CGAT installation page. 
Here's the message that the script requested I passed along. 

Please copy and paste this error and report it via Git Hub: 
 https://github.com/CGATOxford/cgat/issues 

 Debugging: 
 CFLAGS: 
 CPATH: 
 C_INCLUDE_PATH: 
 CPLUS_INCLUDE_PATH: 
 LIBRARY_PATH: 
 LD_LIBRARY_PATH: 
 CGAT_HOME: /Users/ap6/cgat-install
 CONDA_INSTALL_DIR: /Users/ap6/cgat-install/conda-install
 CONDA_INSTALL_TYPE: cgat-scripts
 CONDA_INSTALL_ENV: cgat-s
 PYTHONPATH: 
 INSTALL_BRANCH: master
 RELEASE: 
 CODE_DOWNLOAD_TYPE: 0

**Comment by Charlie-George** [comment]
Hi, 

would you mind pasting the conda command you used and the link to the cgat installation page that you followed the instructions from? 

What operating system are you trying to install on? OX? 

Thanks

**Comment by Acribbs** [comment]
Hi @avp25 , this is actually the old CGATOxford repository, for the newest version of the code in cgat-developers please use this https://github.com/cgat-developers/cgat-apps. 

To install you should be able to simply run: 
`conda install -c bioconda cgat-apps `

**Comment by ghost** [comment]
Hi Adam, 

Sorry for not getting back to you earlier. I will try this installation next time. As for now, I have CGAT working 'somehow' so all is good.

Thank you for your help
Anna

**Comment by Acribbs** [comment]
Hi @avp25, no problem At the moment I think the bioconda cgat-apps is actually broken because of python 3.7 and cython issue. We are currently working to fix it. 

Great that its fixed, I will close this issue.
