### ISSUE TITLE
bam2wiggle.py test

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/cgat#78]
Hi all,

There is an issue when testing bam2wiggle.py. This error message appears on the log file:
```
AssertionError: files /tmp/tmp1k5Cnk/paired_shiftextend.bw and tests/bam2wiggle.py/paired_shiftextend.bw are not the same: /bin/bash -c ' python /home/travis/build/CGATOxford/cgat/scripts/bam2wiggle.py  --output-format=bigwig --wiggle-span=10 --shift-size=50 --extend=150 --output-filename-pattern=paired_shiftextend.bw /home/travis/build/CGATOxford/cgat/tests/bam2wiggle.py/paired.bam > /tmp/tmp1k5Cnk/stdout'
```

From previous tests in a virtual machine I checked that the error was related to high RAM usage. My guess is that not every virtual machine on Travis has the same RAM size and therefore some builds end successfully:
https://travis-ci.org/CGATOxford/cgat/builds/42399068

while others don't:
https://travis-ci.org/CGATOxford/cgat/builds/42619247

Could the script's author please substitute the current test with another one using less RAM memory?

Many thanks!

**Comment by AndreasHeger** [comment]
This has been fixed.
