### ISSUE TITLE
Suggestions for data2spike

### ISSUE THREAD

**Issue by AndreasHeger** [CGATOxford/cgat#82]
Hi Tom,

I think the script is very well done!  I have made some minor changes in the script.

Please find below some suggestions:

1. Make the design table compatible with our other design tables (i.e. no spike column).
Rather, add column names or a regex for selecting the columns to be "spiked" (default is all?). 
This way users need not create separate spike design file.

2. Rename. "Data" is too generic, spike too specific. counts2counts? The script runExpression.py
is going that way as well. Additional operations on counts tables are filtering or other transformations.

Best wishes,
Andreas

**Comment by TomSmithCGAT** [comment]
data2spike.py now takes a standard format design table (as per runExpression.py). A seperate issue has been raised to merge data2spike.py and runExpression.py into counts2counts.py
