### ISSUE TITLE
SGE configuraiton and pipeline portability

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#86]
I've been busy trying to get our pipelines running on our system here and have immediately run into some issues.

* Firstly, and most trivially, our queues are called something different. This can be sorted by overriding the standard queue name by adding a cluster config section to pipeline.ini.

* Secondly, our parallel environments are called something different. and we have lots of them. It seems that the parallel environment most similar to our dedicated is called `openmp`, which is supposed to be for multi-threaded applications created using the OpenMp library. I have no idea if things like `bowtie` and `star` use openmp, nor do I know if its important. I can grep out all of the `-pe dedicated` strings in the Pipelines and replace with `-pe openmp`, but then I'm effectively forking the repository and making it more difficult to push changes back upstream. 

* Thirdly, the resources used to control memory here are `mem` and `vmem` rather than `mem_free`. Again, this could be changed with a grep, but would constitute an incompatible fork. 

* Head nodes here do not have the same environment as worker nodes. No modules are available on the head nodes. This means that worker nodes must explicitly load the modules they need in a qsub script. Note that `qsub` jobs don't by default execute `.bashrc`. This could be solved by allowing a site specific blurb to be added to the job submission script. 
 
* Finally, and most complicatedly, jobs using the openmp dedicated environment have to use the openmp.q queue. I don't know of any way currently to alter the queue in response to the pe environment in Pipeline.py. 

I suggest that we try to remove these hard coded choices. Configuration values would be stored in a site-wide configuration, or by adding the cluster section to all `pipeline.ini`s. Instead of requesting that jobs are run with particular `job_options`, flags such as `threads=` or `mem=` would be set. These would then be picked up by `Pipeline.py` which would query the configuration to work out how to handle them.

**Comment by AndreasHeger** [comment]
@IanSudbery, I have removed all references to "dedicated" in modules and pipelines.

I will also parameterize the mem_free/vmem issue. However, PE+Queue combination will be tricky unless
adding a whole additional layer between the Pipelines and the Queuing system.

**Comment by IanSudbery** [comment]
I have implimented this functinality into Pipeline. 

ini files or .cgat can now contain queues for parrellel jobs.
