### ISSUE TITLE
Memory Usage by fasta2table.py

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#88]
Hi All,

Just trying to get pipeline_annotations running here, and i've run into this problem: 

``` python-traceback
Traceback (most recent call last):
  File "/home/mb1ims/devel/cgat/scripts/fasta2table.py", line 310, in <module>
    sys.exit(main(sys.argv))
  File "/home/mb1ims/devel/cgat/scripts/fasta2table.py", line 294, in main
    s.loadSequence(sequence, options.seqtype)
  File "/home/mb1ims/devel/cgat/CGAT/SequenceProperties.py", line 357, in loadSequence
    SequencePropertiesDN.loadSequence(self, sequence, seqtype)
  File "/home/mb1ims/devel/cgat/CGAT/SequenceProperties.py", line 313, in loadSequence
    for dinuc in [sequence[x - 2:x] for x in range(2, len(sequence) + 1, 1)]:
MemoryError
```

A quick memory profile of this reveals that fasta2table.py is getting upto 40Gb memory usage before failing:

```
152.77user 5.07system 2:41.27elapsed 97%CPU (0avgtext+0avgdata 40636160maxresident)k
0inputs+0outputs (0major+1791557minor)pagefaults 0swaps
```

 This is actaully beyond what we are allowed to request of systems here, and does seem a little extreme for something that is just supposed to be calculating the CpG frequency. 
Ian

**Comment by IanSudbery** [comment]
Converting to xrange should help there right?



Ian





*From:* Andreas Heger [mailto:notifications@github.com]
*Sent:* 07 January 2015 13:59
*To:* CGATOxford/cgat
*Cc:* Ian Sudbery
*Subject:* Re: [cgat] Memory Usage by fasta2table.py (#88)



@IanSudbery <https://github.com/IanSudbery>

thanks, one remaining problem is the usage of range(), which creates a list
in python 2.7.
Using those means that the human genome can be done in 4Gb.

The other is reading in genomic fasta files. Currently these are read as
python strings.

—
Reply to this email directly or view it on GitHub
<https://github.com/CGATOxford/cgat/issues/88#issuecomment-69024591>.

**Comment by AndreasHeger** [comment]
Indeed. I have done this, but not yet committed.

Best, Andreas
