### ISSUE TITLE
ggplot incompatible with cluster submission in Expression.py

### ISSUE THREAD

**Issue by MikeDMorgan** [CGATOxford/cgat#89]
Currently Expression.py makes use of the python ggplot library which requires gtk.  Suggest using R ggplot.  This is causing problems for other scripts and modules that import Expression.py, even if they are not explicitly using it or the particular functions that use ggplot.

Is there a way of using an alternative backend for ggplot as there is with matplotlib?

**Comment by AndreasHeger** [comment]
@MikeDMorgan, python ggplot uses matplotlib under the hood and thus the same backend settings apply.

I have been trying to move to pandas/ggplot instead of R in Expression.py as the code looks cleaner and is easier to debug.
