### ISSUE TITLE
annotations pipeline.ini incompatible with pipeline_intervals

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#90]
Running pipeline_intervals using hg19_ensembl75 annotations produces the following error

```python-traceback

Traceback (most recent call last):
    File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ruffus/task.py", line 743, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
    File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ruffus/task.py", line 541, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
    File "/ifs/devel/Ian/cgat/CGATPipelines/pipeline_intervals.py", line 701, in annotateTSS
        PARAMS["annotations_interface_geneset_coding_gene_tss_bed"])
    KeyError: 'annotations_interface_geneset_coding_gene_tss_bed'
```

This is due to the interface section on the annotations pipeline pipeline.ini being rearranged (isn't the point of an interface that it doesn't change?). All the tss files now start tts_ but there doesn't seem to be an equivalent one for coding genes. The closest is tss_gene_bed. Should I substitute this?

Ian
---

**Comment by AndreasHeger** [comment]
@IanSudbery, the tss sections have changed more thoroughly as there was no consistency in the files generated previously. I will fix.

**Comment by AndreasHeger** [comment]
@IanSudbery, I don't think there is an easy fix. The solution is to re-run the annotations pipeline.
