### ISSUE TITLE
Multiple methods options to gtf2gtf

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#93]
When executing gtf2gtf the commandline will accept multiple entries for --method. However, only the last one is actually used and no warning is given, nor is it stated in the documentation that only one method can be specified. In some other scripts, multiple manipulations can be specified on a single commandline. (the optparse action is append rather than store).

**Comment by AndreasHeger** [comment]
@IanSudbery, unfortunately that is a feature of optarg. You can specify the same argument multiple times, only the last is used. This should be true for not just for --method, but any of the other options as well.
By setting action="append", multiple calls are appended, but I don't see a way to raise an Error.

**Comment by IanSudbery** [comment]
My problem is more one of consitancy:
Some tools, like for example bed2bed, will take multiple methods and use all of them, running multiple processing steps in a single call, while others, like gtf2gtf will take multiple methods, but only use one of them. There seems to be no documentation as to which tools do which.

The simplest solution I suppose, would be to require all tools to only take a single method and enforce multiple calls for multiple steps (this would also make processing order more explicit). An alternative I suppose would be for those that only take a single method to use append and then manually check if more than one method has been supplied.

**Comment by AndreasHeger** [comment]
I agree that consistency would be good, but I don't want to rule out for some tools to implement optimizations by applying multiple operations in one go. Only allowing one method would mean onerous reparsing steps between multiple steps that could be avoided.

I have briefly looked into providing a check to optparse, but it seems a headache to implement.

**Comment by sebastian-luna-valero** [comment]
Should we move away from optparse to argparse in the next scrum?

optparse is deprecated in Python 2.7 in favour of argparse:
https://docs.python.org/2/library/optparse.html

Best regards,
Sebastian.


2015-01-16 15:09 GMT+00:00 Andreas Heger <notifications@github.com>:

**Comment by AndreasHeger** [comment]
We looked at that last time and thought it would not be worth the effort.

Best wishes,
Andreas

**Comment by IanSudbery** [comment]
Why not allow multiple methods in gtf2gtf? is this because differing orders makes the results too unpredictable?

A check on a case by case basis would be fairly easy, or simply stating in the documentation which is correct would be better than nothing?

See d1b93db0759f453a67fef362cd886cac5abf7310

**Comment by AndreasHeger** [comment]
The problem with gtf2gtf is that different methods require the input stream to be sorted in different ways. Either you always sort, breaking the ability to process in a stream and possibly wasting resources (why sort if it is already sorted) or you ask the user to sort as needed (which is what we currently do).

**Comment by IanSudbery** [comment]
I think in this case then the best solution is just to put a warning in the documentation. See my commit above.

**Comment by AndreasHeger** [comment]
Thanks, that is great. There some typos in Pipeline.py
