### ISSUE TITLE
input file issue with pipeline_rnaseqtranscripts.py

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#94]
Hi

pipeline_rnaseqtranscripts.py have some issue to find the file geneset_all.gtf.gz used by buildReferenceGeneSet.

when I configure the following parameters in pipeline.ini

like this (1)
directory with annotation information
dir=/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS

I have this error:

No way to run job: Input file '/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS/geneset_all.gtf.gz' does not exist 

like this (2)

directory with annotation information
dir=/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS/ensembl.dir

I have this error:
No way to run job: Input file '/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS/ensembl.dir/ensembl.dir/geneset_all.gtf.gz' does not exist 

I updated the pipeline.

Cynthia

**Comment by AndreasHeger** [comment]
@csandorfr , thanks. Recently the layout of the annotations pipeline has changed. The configuration should be (1):

dir=/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS

but you might need to re-run the annotations pipeline to create the correct files.

**Comment by csandorfr** [comment]
Thanks

OK it doesn't work with dir=/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS

I have this error: No way to run job: Input file '/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS/geneset_all.gtf.gz' does not exist 

I'm updating the pipelines and I will re run pipeline_annotations.py

**Comment by csandorfr** [comment]
I updated my version of CGAT pipelines (with git, the date of file changed). I re-ran the pipeline_annotations. However I have still the same error:

check_input_files_exist (*param)
                                                       File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/ruffus/file_name_parameters.py", line 381, in check_input_files_exist
                                                         "Input file '%s' does not exist" % f)
                                                     MissingInputFileError:     
                                                         
                                                         
                                                         No way to run job: Input file '/net/isi-scratch/cynthia/DATA/Parkinson/RNAseq/bsg-ftp.well.ox.ac.uk/ANNOTATIONS2/geneset_all.gtf.gz' does not exist
