### ISSUE TITLE
Strand specificity in bed2bed

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#95]
Currently bed2bed.py does not take strand into account when merging intervals. The ability to do this would be of use. bedtools merge can be strand specific, but not cannot handle bed12 files properly.

**Comment by IanSudbery** [comment]
Suggested code in a5fb98bc4263ccdafaf1774111d664fd0dc97f6f.

In general the idea is to keep two lists of currently overlapping intervals, one for each strand. One possible issue I can see is that the output might not be sorted. 

I'd appreciate someone taking a peek at my reasoning ( @AndreasHeger ?)

**Comment by IanSudbery** [comment]
Oops, wrong commit 75ffd40c5ef1619333191187784d3c6999576277

**Comment by AndreasHeger** [comment]
@IanSudbery, thanks for suggesting this. I think your reasoning is fine. Do you have a unit test case?

**Comment by IanSudbery** [comment]
I'll add one. My main worry was that it didn't change the output in anyway when not switched on. As far as I can see it doesn't (or at least all the existing tests still pass).
