### ISSUE TITLE
Restricting tests

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#96]
Restricting tests no longer seems to work.

I have a file test_scripts.yaml in my test directory that looks like this:
```
restrict:
   regex: bed2bed.py
```

yet running:

```
nosetests -v tests/test_scripts.py
```
Runs all tests, which can be very annoying as it takes a long time to run all the tests and when you are trying to sort out a problem with a single test, it really makes things slow.

Ian

**Comment by AndreasHeger** [comment]
Hi Ian,

it should be _test_scripts.yaml?

Maybe a different name would be better. The idea is that this file should not be part of the repository.

Best wishes,
Andreas

**Comment by MikeDMorgan** [comment]
Perhaps adding files like this to .gitignore would be good practise?

Regards
Mike
On 01/15/15 12:52, Andreas Heger wrote:
>
> Hi Ian,
>
> it should be _test_scripts.yaml?
>
> Maybe a different name would be better. The idea is that this file 
> should not be part of the repository.
>
> Best wishes,
> Andreas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CGATOxford/cgat/issues/96#issuecomment-70081247>.
>

-- 
CGAT Genomics Training Fellow
MRC Functional Genomics Unit
University of Oxford
+44 1865 282362

**Comment by AndreasHeger** [comment]
It already is.

**Comment by IanSudbery** [comment]
Cheers.
